// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module image_diff_posterize_Read_Loop_proc_Pipeline_Read_Loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RFIFONUM,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RFIFONUM,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        add_ln41_1_i,
        add_ln41_i,
        image_diff_posterize_rowA_0_address0,
        image_diff_posterize_rowA_0_ce0,
        image_diff_posterize_rowA_0_we0,
        image_diff_posterize_rowA_0_d0,
        image_diff_posterize_rowB_0_address0,
        image_diff_posterize_rowB_0_ce0,
        image_diff_posterize_rowB_0_we0,
        image_diff_posterize_rowB_0_d0,
        image_diff_posterize_rowA_1_address0,
        image_diff_posterize_rowA_1_ce0,
        image_diff_posterize_rowA_1_we0,
        image_diff_posterize_rowA_1_d0,
        image_diff_posterize_rowB_1_address0,
        image_diff_posterize_rowB_1_ce0,
        image_diff_posterize_rowB_1_we0,
        image_diff_posterize_rowB_1_d0,
        image_diff_posterize_rowA_2_address0,
        image_diff_posterize_rowA_2_ce0,
        image_diff_posterize_rowA_2_we0,
        image_diff_posterize_rowA_2_d0,
        image_diff_posterize_rowB_2_address0,
        image_diff_posterize_rowB_2_ce0,
        image_diff_posterize_rowB_2_we0,
        image_diff_posterize_rowB_2_d0,
        image_diff_posterize_rowA_3_address0,
        image_diff_posterize_rowA_3_ce0,
        image_diff_posterize_rowA_3_we0,
        image_diff_posterize_rowA_3_d0,
        image_diff_posterize_rowB_3_address0,
        image_diff_posterize_rowB_3_ce0,
        image_diff_posterize_rowB_3_we0,
        image_diff_posterize_rowB_3_d0,
        image_diff_posterize_rowA_4_address0,
        image_diff_posterize_rowA_4_ce0,
        image_diff_posterize_rowA_4_we0,
        image_diff_posterize_rowA_4_d0,
        image_diff_posterize_rowB_4_address0,
        image_diff_posterize_rowB_4_ce0,
        image_diff_posterize_rowB_4_we0,
        image_diff_posterize_rowB_4_d0,
        image_diff_posterize_rowA_5_address0,
        image_diff_posterize_rowA_5_ce0,
        image_diff_posterize_rowA_5_we0,
        image_diff_posterize_rowA_5_d0,
        image_diff_posterize_rowB_5_address0,
        image_diff_posterize_rowB_5_ce0,
        image_diff_posterize_rowB_5_we0,
        image_diff_posterize_rowB_5_d0,
        image_diff_posterize_rowA_6_address0,
        image_diff_posterize_rowA_6_ce0,
        image_diff_posterize_rowA_6_we0,
        image_diff_posterize_rowA_6_d0,
        image_diff_posterize_rowB_6_address0,
        image_diff_posterize_rowB_6_ce0,
        image_diff_posterize_rowB_6_we0,
        image_diff_posterize_rowB_6_d0,
        image_diff_posterize_rowA_7_address0,
        image_diff_posterize_rowA_7_ce0,
        image_diff_posterize_rowA_7_we0,
        image_diff_posterize_rowA_7_d0,
        image_diff_posterize_rowB_7_address0,
        image_diff_posterize_rowB_7_ce0,
        image_diff_posterize_rowB_7_we0,
        image_diff_posterize_rowB_7_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [63:0] m_axi_gmem0_AWADDR;
output  [0:0] m_axi_gmem0_AWID;
output  [31:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [0:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [7:0] m_axi_gmem0_WDATA;
output  [0:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [0:0] m_axi_gmem0_WID;
output  [0:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [63:0] m_axi_gmem0_ARADDR;
output  [0:0] m_axi_gmem0_ARID;
output  [31:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [0:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [7:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [0:0] m_axi_gmem0_RID;
input  [10:0] m_axi_gmem0_RFIFONUM;
input  [0:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [0:0] m_axi_gmem0_BID;
input  [0:0] m_axi_gmem0_BUSER;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [63:0] m_axi_gmem1_AWADDR;
output  [0:0] m_axi_gmem1_AWID;
output  [31:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [0:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [7:0] m_axi_gmem1_WDATA;
output  [0:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [0:0] m_axi_gmem1_WID;
output  [0:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [63:0] m_axi_gmem1_ARADDR;
output  [0:0] m_axi_gmem1_ARID;
output  [31:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [0:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [7:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [0:0] m_axi_gmem1_RID;
input  [10:0] m_axi_gmem1_RFIFONUM;
input  [0:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [0:0] m_axi_gmem1_BID;
input  [0:0] m_axi_gmem1_BUSER;
input  [63:0] add_ln41_1_i;
input  [63:0] add_ln41_i;
output  [4:0] image_diff_posterize_rowA_0_address0;
output   image_diff_posterize_rowA_0_ce0;
output   image_diff_posterize_rowA_0_we0;
output  [7:0] image_diff_posterize_rowA_0_d0;
output  [4:0] image_diff_posterize_rowB_0_address0;
output   image_diff_posterize_rowB_0_ce0;
output   image_diff_posterize_rowB_0_we0;
output  [7:0] image_diff_posterize_rowB_0_d0;
output  [4:0] image_diff_posterize_rowA_1_address0;
output   image_diff_posterize_rowA_1_ce0;
output   image_diff_posterize_rowA_1_we0;
output  [7:0] image_diff_posterize_rowA_1_d0;
output  [4:0] image_diff_posterize_rowB_1_address0;
output   image_diff_posterize_rowB_1_ce0;
output   image_diff_posterize_rowB_1_we0;
output  [7:0] image_diff_posterize_rowB_1_d0;
output  [4:0] image_diff_posterize_rowA_2_address0;
output   image_diff_posterize_rowA_2_ce0;
output   image_diff_posterize_rowA_2_we0;
output  [7:0] image_diff_posterize_rowA_2_d0;
output  [4:0] image_diff_posterize_rowB_2_address0;
output   image_diff_posterize_rowB_2_ce0;
output   image_diff_posterize_rowB_2_we0;
output  [7:0] image_diff_posterize_rowB_2_d0;
output  [4:0] image_diff_posterize_rowA_3_address0;
output   image_diff_posterize_rowA_3_ce0;
output   image_diff_posterize_rowA_3_we0;
output  [7:0] image_diff_posterize_rowA_3_d0;
output  [4:0] image_diff_posterize_rowB_3_address0;
output   image_diff_posterize_rowB_3_ce0;
output   image_diff_posterize_rowB_3_we0;
output  [7:0] image_diff_posterize_rowB_3_d0;
output  [4:0] image_diff_posterize_rowA_4_address0;
output   image_diff_posterize_rowA_4_ce0;
output   image_diff_posterize_rowA_4_we0;
output  [7:0] image_diff_posterize_rowA_4_d0;
output  [4:0] image_diff_posterize_rowB_4_address0;
output   image_diff_posterize_rowB_4_ce0;
output   image_diff_posterize_rowB_4_we0;
output  [7:0] image_diff_posterize_rowB_4_d0;
output  [4:0] image_diff_posterize_rowA_5_address0;
output   image_diff_posterize_rowA_5_ce0;
output   image_diff_posterize_rowA_5_we0;
output  [7:0] image_diff_posterize_rowA_5_d0;
output  [4:0] image_diff_posterize_rowB_5_address0;
output   image_diff_posterize_rowB_5_ce0;
output   image_diff_posterize_rowB_5_we0;
output  [7:0] image_diff_posterize_rowB_5_d0;
output  [4:0] image_diff_posterize_rowA_6_address0;
output   image_diff_posterize_rowA_6_ce0;
output   image_diff_posterize_rowA_6_we0;
output  [7:0] image_diff_posterize_rowA_6_d0;
output  [4:0] image_diff_posterize_rowB_6_address0;
output   image_diff_posterize_rowB_6_ce0;
output   image_diff_posterize_rowB_6_we0;
output  [7:0] image_diff_posterize_rowB_6_d0;
output  [4:0] image_diff_posterize_rowA_7_address0;
output   image_diff_posterize_rowA_7_ce0;
output   image_diff_posterize_rowA_7_we0;
output  [7:0] image_diff_posterize_rowA_7_d0;
output  [4:0] image_diff_posterize_rowB_7_address0;
output   image_diff_posterize_rowB_7_ce0;
output   image_diff_posterize_rowB_7_we0;
output  [7:0] image_diff_posterize_rowB_7_d0;

reg ap_idle;
reg m_axi_gmem0_RREADY;
reg m_axi_gmem1_RREADY;
reg image_diff_posterize_rowA_0_ce0;
reg image_diff_posterize_rowA_0_we0;
reg image_diff_posterize_rowB_0_ce0;
reg image_diff_posterize_rowB_0_we0;
reg image_diff_posterize_rowA_1_ce0;
reg image_diff_posterize_rowA_1_we0;
reg image_diff_posterize_rowB_1_ce0;
reg image_diff_posterize_rowB_1_we0;
reg image_diff_posterize_rowA_2_ce0;
reg image_diff_posterize_rowA_2_we0;
reg image_diff_posterize_rowB_2_ce0;
reg image_diff_posterize_rowB_2_we0;
reg image_diff_posterize_rowA_3_ce0;
reg image_diff_posterize_rowA_3_we0;
reg image_diff_posterize_rowB_3_ce0;
reg image_diff_posterize_rowB_3_we0;
reg image_diff_posterize_rowA_4_ce0;
reg image_diff_posterize_rowA_4_we0;
reg image_diff_posterize_rowB_4_ce0;
reg image_diff_posterize_rowB_4_we0;
reg image_diff_posterize_rowA_5_ce0;
reg image_diff_posterize_rowA_5_we0;
reg image_diff_posterize_rowB_5_ce0;
reg image_diff_posterize_rowB_5_we0;
reg image_diff_posterize_rowA_6_ce0;
reg image_diff_posterize_rowA_6_we0;
reg image_diff_posterize_rowB_6_ce0;
reg image_diff_posterize_rowB_6_we0;
reg image_diff_posterize_rowA_7_ce0;
reg image_diff_posterize_rowA_7_we0;
reg image_diff_posterize_rowB_7_ce0;
reg image_diff_posterize_rowB_7_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln47_fu_356_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem1_blk_n_R;
wire    ap_block_pp0_stage0;
reg    gmem0_blk_n_R;
reg    ap_block_pp0_stage0_11001;
reg   [4:0] lshr_ln_i_reg_427;
reg   [4:0] lshr_ln_i_reg_427_pp0_iter1_reg;
wire   [2:0] trunc_ln50_fu_378_p1;
reg   [2:0] trunc_ln50_reg_432;
reg   [2:0] trunc_ln50_reg_432_pp0_iter1_reg;
reg   [7:0] gmem0_addr_read_reg_436;
reg   [7:0] gmem1_addr_read_reg_448;
wire   [63:0] zext_ln50_fu_387_p1;
reg   [8:0] j_fu_102;
wire   [8:0] add_ln47_fu_362_p2;
wire    ap_loop_init;
reg   [8:0] ap_sig_allocacmp_j_2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

image_diff_posterize_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln47_fu_356_p2 == 1'd0))) begin
            j_fu_102 <= add_ln47_fu_362_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_102 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        gmem0_addr_read_reg_436 <= m_axi_gmem0_RDATA;
        gmem1_addr_read_reg_448 <= m_axi_gmem1_RDATA;
        lshr_ln_i_reg_427_pp0_iter1_reg <= lshr_ln_i_reg_427;
        trunc_ln50_reg_432_pp0_iter1_reg <= trunc_ln50_reg_432;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln47_fu_356_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        lshr_ln_i_reg_427 <= {{ap_sig_allocacmp_j_2[7:3]}};
        trunc_ln50_reg_432 <= trunc_ln50_fu_378_p1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln47_fu_356_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_j_2 = 9'd0;
    end else begin
        ap_sig_allocacmp_j_2 = j_fu_102;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem0_blk_n_R = m_axi_gmem0_RVALID;
    end else begin
        gmem0_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem1_blk_n_R = m_axi_gmem1_RVALID;
    end else begin
        gmem1_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        image_diff_posterize_rowA_0_ce0 = 1'b1;
    end else begin
        image_diff_posterize_rowA_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln50_reg_432_pp0_iter1_reg == 3'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        image_diff_posterize_rowA_0_we0 = 1'b1;
    end else begin
        image_diff_posterize_rowA_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        image_diff_posterize_rowA_1_ce0 = 1'b1;
    end else begin
        image_diff_posterize_rowA_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln50_reg_432_pp0_iter1_reg == 3'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        image_diff_posterize_rowA_1_we0 = 1'b1;
    end else begin
        image_diff_posterize_rowA_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        image_diff_posterize_rowA_2_ce0 = 1'b1;
    end else begin
        image_diff_posterize_rowA_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln50_reg_432_pp0_iter1_reg == 3'd2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        image_diff_posterize_rowA_2_we0 = 1'b1;
    end else begin
        image_diff_posterize_rowA_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        image_diff_posterize_rowA_3_ce0 = 1'b1;
    end else begin
        image_diff_posterize_rowA_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln50_reg_432_pp0_iter1_reg == 3'd3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        image_diff_posterize_rowA_3_we0 = 1'b1;
    end else begin
        image_diff_posterize_rowA_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        image_diff_posterize_rowA_4_ce0 = 1'b1;
    end else begin
        image_diff_posterize_rowA_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln50_reg_432_pp0_iter1_reg == 3'd4) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        image_diff_posterize_rowA_4_we0 = 1'b1;
    end else begin
        image_diff_posterize_rowA_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        image_diff_posterize_rowA_5_ce0 = 1'b1;
    end else begin
        image_diff_posterize_rowA_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln50_reg_432_pp0_iter1_reg == 3'd5) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        image_diff_posterize_rowA_5_we0 = 1'b1;
    end else begin
        image_diff_posterize_rowA_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        image_diff_posterize_rowA_6_ce0 = 1'b1;
    end else begin
        image_diff_posterize_rowA_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln50_reg_432_pp0_iter1_reg == 3'd6) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        image_diff_posterize_rowA_6_we0 = 1'b1;
    end else begin
        image_diff_posterize_rowA_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        image_diff_posterize_rowA_7_ce0 = 1'b1;
    end else begin
        image_diff_posterize_rowA_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln50_reg_432_pp0_iter1_reg == 3'd7) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        image_diff_posterize_rowA_7_we0 = 1'b1;
    end else begin
        image_diff_posterize_rowA_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        image_diff_posterize_rowB_0_ce0 = 1'b1;
    end else begin
        image_diff_posterize_rowB_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln50_reg_432_pp0_iter1_reg == 3'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        image_diff_posterize_rowB_0_we0 = 1'b1;
    end else begin
        image_diff_posterize_rowB_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        image_diff_posterize_rowB_1_ce0 = 1'b1;
    end else begin
        image_diff_posterize_rowB_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln50_reg_432_pp0_iter1_reg == 3'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        image_diff_posterize_rowB_1_we0 = 1'b1;
    end else begin
        image_diff_posterize_rowB_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        image_diff_posterize_rowB_2_ce0 = 1'b1;
    end else begin
        image_diff_posterize_rowB_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln50_reg_432_pp0_iter1_reg == 3'd2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        image_diff_posterize_rowB_2_we0 = 1'b1;
    end else begin
        image_diff_posterize_rowB_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        image_diff_posterize_rowB_3_ce0 = 1'b1;
    end else begin
        image_diff_posterize_rowB_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln50_reg_432_pp0_iter1_reg == 3'd3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        image_diff_posterize_rowB_3_we0 = 1'b1;
    end else begin
        image_diff_posterize_rowB_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        image_diff_posterize_rowB_4_ce0 = 1'b1;
    end else begin
        image_diff_posterize_rowB_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln50_reg_432_pp0_iter1_reg == 3'd4) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        image_diff_posterize_rowB_4_we0 = 1'b1;
    end else begin
        image_diff_posterize_rowB_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        image_diff_posterize_rowB_5_ce0 = 1'b1;
    end else begin
        image_diff_posterize_rowB_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln50_reg_432_pp0_iter1_reg == 3'd5) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        image_diff_posterize_rowB_5_we0 = 1'b1;
    end else begin
        image_diff_posterize_rowB_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        image_diff_posterize_rowB_6_ce0 = 1'b1;
    end else begin
        image_diff_posterize_rowB_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln50_reg_432_pp0_iter1_reg == 3'd6) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        image_diff_posterize_rowB_6_we0 = 1'b1;
    end else begin
        image_diff_posterize_rowB_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        image_diff_posterize_rowB_7_ce0 = 1'b1;
    end else begin
        image_diff_posterize_rowB_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln50_reg_432_pp0_iter1_reg == 3'd7) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        image_diff_posterize_rowB_7_we0 = 1'b1;
    end else begin
        image_diff_posterize_rowB_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem0_RREADY = 1'b1;
    end else begin
        m_axi_gmem0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem1_RREADY = 1'b1;
    end else begin
        m_axi_gmem1_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln47_fu_362_p2 = (ap_sig_allocacmp_j_2 + 9'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((m_axi_gmem0_RVALID == 1'b0) | (m_axi_gmem1_RVALID == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((m_axi_gmem0_RVALID == 1'b0) | (m_axi_gmem1_RVALID == 1'b0)));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((m_axi_gmem0_RVALID == 1'b0) | (m_axi_gmem1_RVALID == 1'b0));
end

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln47_fu_356_p2 = ((ap_sig_allocacmp_j_2 == 9'd256) ? 1'b1 : 1'b0);

assign image_diff_posterize_rowA_0_address0 = zext_ln50_fu_387_p1;

assign image_diff_posterize_rowA_0_d0 = gmem0_addr_read_reg_436;

assign image_diff_posterize_rowA_1_address0 = zext_ln50_fu_387_p1;

assign image_diff_posterize_rowA_1_d0 = gmem0_addr_read_reg_436;

assign image_diff_posterize_rowA_2_address0 = zext_ln50_fu_387_p1;

assign image_diff_posterize_rowA_2_d0 = gmem0_addr_read_reg_436;

assign image_diff_posterize_rowA_3_address0 = zext_ln50_fu_387_p1;

assign image_diff_posterize_rowA_3_d0 = gmem0_addr_read_reg_436;

assign image_diff_posterize_rowA_4_address0 = zext_ln50_fu_387_p1;

assign image_diff_posterize_rowA_4_d0 = gmem0_addr_read_reg_436;

assign image_diff_posterize_rowA_5_address0 = zext_ln50_fu_387_p1;

assign image_diff_posterize_rowA_5_d0 = gmem0_addr_read_reg_436;

assign image_diff_posterize_rowA_6_address0 = zext_ln50_fu_387_p1;

assign image_diff_posterize_rowA_6_d0 = gmem0_addr_read_reg_436;

assign image_diff_posterize_rowA_7_address0 = zext_ln50_fu_387_p1;

assign image_diff_posterize_rowA_7_d0 = gmem0_addr_read_reg_436;

assign image_diff_posterize_rowB_0_address0 = zext_ln50_fu_387_p1;

assign image_diff_posterize_rowB_0_d0 = gmem1_addr_read_reg_448;

assign image_diff_posterize_rowB_1_address0 = zext_ln50_fu_387_p1;

assign image_diff_posterize_rowB_1_d0 = gmem1_addr_read_reg_448;

assign image_diff_posterize_rowB_2_address0 = zext_ln50_fu_387_p1;

assign image_diff_posterize_rowB_2_d0 = gmem1_addr_read_reg_448;

assign image_diff_posterize_rowB_3_address0 = zext_ln50_fu_387_p1;

assign image_diff_posterize_rowB_3_d0 = gmem1_addr_read_reg_448;

assign image_diff_posterize_rowB_4_address0 = zext_ln50_fu_387_p1;

assign image_diff_posterize_rowB_4_d0 = gmem1_addr_read_reg_448;

assign image_diff_posterize_rowB_5_address0 = zext_ln50_fu_387_p1;

assign image_diff_posterize_rowB_5_d0 = gmem1_addr_read_reg_448;

assign image_diff_posterize_rowB_6_address0 = zext_ln50_fu_387_p1;

assign image_diff_posterize_rowB_6_d0 = gmem1_addr_read_reg_448;

assign image_diff_posterize_rowB_7_address0 = zext_ln50_fu_387_p1;

assign image_diff_posterize_rowB_7_d0 = gmem1_addr_read_reg_448;

assign m_axi_gmem0_ARADDR = 64'd0;

assign m_axi_gmem0_ARBURST = 2'd0;

assign m_axi_gmem0_ARCACHE = 4'd0;

assign m_axi_gmem0_ARID = 1'd0;

assign m_axi_gmem0_ARLEN = 32'd0;

assign m_axi_gmem0_ARLOCK = 2'd0;

assign m_axi_gmem0_ARPROT = 3'd0;

assign m_axi_gmem0_ARQOS = 4'd0;

assign m_axi_gmem0_ARREGION = 4'd0;

assign m_axi_gmem0_ARSIZE = 3'd0;

assign m_axi_gmem0_ARUSER = 1'd0;

assign m_axi_gmem0_ARVALID = 1'b0;

assign m_axi_gmem0_AWADDR = 64'd0;

assign m_axi_gmem0_AWBURST = 2'd0;

assign m_axi_gmem0_AWCACHE = 4'd0;

assign m_axi_gmem0_AWID = 1'd0;

assign m_axi_gmem0_AWLEN = 32'd0;

assign m_axi_gmem0_AWLOCK = 2'd0;

assign m_axi_gmem0_AWPROT = 3'd0;

assign m_axi_gmem0_AWQOS = 4'd0;

assign m_axi_gmem0_AWREGION = 4'd0;

assign m_axi_gmem0_AWSIZE = 3'd0;

assign m_axi_gmem0_AWUSER = 1'd0;

assign m_axi_gmem0_AWVALID = 1'b0;

assign m_axi_gmem0_BREADY = 1'b0;

assign m_axi_gmem0_WDATA = 8'd0;

assign m_axi_gmem0_WID = 1'd0;

assign m_axi_gmem0_WLAST = 1'b0;

assign m_axi_gmem0_WSTRB = 1'd0;

assign m_axi_gmem0_WUSER = 1'd0;

assign m_axi_gmem0_WVALID = 1'b0;

assign m_axi_gmem1_ARADDR = 64'd0;

assign m_axi_gmem1_ARBURST = 2'd0;

assign m_axi_gmem1_ARCACHE = 4'd0;

assign m_axi_gmem1_ARID = 1'd0;

assign m_axi_gmem1_ARLEN = 32'd0;

assign m_axi_gmem1_ARLOCK = 2'd0;

assign m_axi_gmem1_ARPROT = 3'd0;

assign m_axi_gmem1_ARQOS = 4'd0;

assign m_axi_gmem1_ARREGION = 4'd0;

assign m_axi_gmem1_ARSIZE = 3'd0;

assign m_axi_gmem1_ARUSER = 1'd0;

assign m_axi_gmem1_ARVALID = 1'b0;

assign m_axi_gmem1_AWADDR = 64'd0;

assign m_axi_gmem1_AWBURST = 2'd0;

assign m_axi_gmem1_AWCACHE = 4'd0;

assign m_axi_gmem1_AWID = 1'd0;

assign m_axi_gmem1_AWLEN = 32'd0;

assign m_axi_gmem1_AWLOCK = 2'd0;

assign m_axi_gmem1_AWPROT = 3'd0;

assign m_axi_gmem1_AWQOS = 4'd0;

assign m_axi_gmem1_AWREGION = 4'd0;

assign m_axi_gmem1_AWSIZE = 3'd0;

assign m_axi_gmem1_AWUSER = 1'd0;

assign m_axi_gmem1_AWVALID = 1'b0;

assign m_axi_gmem1_BREADY = 1'b0;

assign m_axi_gmem1_WDATA = 8'd0;

assign m_axi_gmem1_WID = 1'd0;

assign m_axi_gmem1_WLAST = 1'b0;

assign m_axi_gmem1_WSTRB = 1'd0;

assign m_axi_gmem1_WUSER = 1'd0;

assign m_axi_gmem1_WVALID = 1'b0;

assign trunc_ln50_fu_378_p1 = ap_sig_allocacmp_j_2[2:0];

assign zext_ln50_fu_387_p1 = lshr_ln_i_reg_427_pp0_iter1_reg;

endmodule //image_diff_posterize_Read_Loop_proc_Pipeline_Read_Loop
