// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module image_diff_posterize_Col_Loop_proc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        image_diff_posterize_rowA_0_address0,
        image_diff_posterize_rowA_0_ce0,
        image_diff_posterize_rowA_0_q0,
        image_diff_posterize_rowA_1_address0,
        image_diff_posterize_rowA_1_ce0,
        image_diff_posterize_rowA_1_q0,
        image_diff_posterize_rowA_2_address0,
        image_diff_posterize_rowA_2_ce0,
        image_diff_posterize_rowA_2_q0,
        image_diff_posterize_rowA_3_address0,
        image_diff_posterize_rowA_3_ce0,
        image_diff_posterize_rowA_3_q0,
        image_diff_posterize_rowA_4_address0,
        image_diff_posterize_rowA_4_ce0,
        image_diff_posterize_rowA_4_q0,
        image_diff_posterize_rowA_5_address0,
        image_diff_posterize_rowA_5_ce0,
        image_diff_posterize_rowA_5_q0,
        image_diff_posterize_rowA_6_address0,
        image_diff_posterize_rowA_6_ce0,
        image_diff_posterize_rowA_6_q0,
        image_diff_posterize_rowA_7_address0,
        image_diff_posterize_rowA_7_ce0,
        image_diff_posterize_rowA_7_q0,
        image_diff_posterize_rowB_0_address0,
        image_diff_posterize_rowB_0_ce0,
        image_diff_posterize_rowB_0_q0,
        image_diff_posterize_rowB_1_address0,
        image_diff_posterize_rowB_1_ce0,
        image_diff_posterize_rowB_1_q0,
        image_diff_posterize_rowB_2_address0,
        image_diff_posterize_rowB_2_ce0,
        image_diff_posterize_rowB_2_q0,
        image_diff_posterize_rowB_3_address0,
        image_diff_posterize_rowB_3_ce0,
        image_diff_posterize_rowB_3_q0,
        image_diff_posterize_rowB_4_address0,
        image_diff_posterize_rowB_4_ce0,
        image_diff_posterize_rowB_4_q0,
        image_diff_posterize_rowB_5_address0,
        image_diff_posterize_rowB_5_ce0,
        image_diff_posterize_rowB_5_q0,
        image_diff_posterize_rowB_6_address0,
        image_diff_posterize_rowB_6_ce0,
        image_diff_posterize_rowB_6_q0,
        image_diff_posterize_rowB_7_address0,
        image_diff_posterize_rowB_7_ce0,
        image_diff_posterize_rowB_7_q0,
        image_diff_posterize_rowC_0_address0,
        image_diff_posterize_rowC_0_ce0,
        image_diff_posterize_rowC_0_we0,
        image_diff_posterize_rowC_0_d0,
        image_diff_posterize_rowC_1_address0,
        image_diff_posterize_rowC_1_ce0,
        image_diff_posterize_rowC_1_we0,
        image_diff_posterize_rowC_1_d0,
        image_diff_posterize_rowC_2_address0,
        image_diff_posterize_rowC_2_ce0,
        image_diff_posterize_rowC_2_we0,
        image_diff_posterize_rowC_2_d0,
        image_diff_posterize_rowC_3_address0,
        image_diff_posterize_rowC_3_ce0,
        image_diff_posterize_rowC_3_we0,
        image_diff_posterize_rowC_3_d0,
        image_diff_posterize_rowC_4_address0,
        image_diff_posterize_rowC_4_ce0,
        image_diff_posterize_rowC_4_we0,
        image_diff_posterize_rowC_4_d0,
        image_diff_posterize_rowC_5_address0,
        image_diff_posterize_rowC_5_ce0,
        image_diff_posterize_rowC_5_we0,
        image_diff_posterize_rowC_5_d0,
        image_diff_posterize_rowC_6_address0,
        image_diff_posterize_rowC_6_ce0,
        image_diff_posterize_rowC_6_we0,
        image_diff_posterize_rowC_6_d0,
        image_diff_posterize_rowC_7_address0,
        image_diff_posterize_rowC_7_ce0,
        image_diff_posterize_rowC_7_we0,
        image_diff_posterize_rowC_7_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [4:0] image_diff_posterize_rowA_0_address0;
output   image_diff_posterize_rowA_0_ce0;
input  [7:0] image_diff_posterize_rowA_0_q0;
output  [4:0] image_diff_posterize_rowA_1_address0;
output   image_diff_posterize_rowA_1_ce0;
input  [7:0] image_diff_posterize_rowA_1_q0;
output  [4:0] image_diff_posterize_rowA_2_address0;
output   image_diff_posterize_rowA_2_ce0;
input  [7:0] image_diff_posterize_rowA_2_q0;
output  [4:0] image_diff_posterize_rowA_3_address0;
output   image_diff_posterize_rowA_3_ce0;
input  [7:0] image_diff_posterize_rowA_3_q0;
output  [4:0] image_diff_posterize_rowA_4_address0;
output   image_diff_posterize_rowA_4_ce0;
input  [7:0] image_diff_posterize_rowA_4_q0;
output  [4:0] image_diff_posterize_rowA_5_address0;
output   image_diff_posterize_rowA_5_ce0;
input  [7:0] image_diff_posterize_rowA_5_q0;
output  [4:0] image_diff_posterize_rowA_6_address0;
output   image_diff_posterize_rowA_6_ce0;
input  [7:0] image_diff_posterize_rowA_6_q0;
output  [4:0] image_diff_posterize_rowA_7_address0;
output   image_diff_posterize_rowA_7_ce0;
input  [7:0] image_diff_posterize_rowA_7_q0;
output  [4:0] image_diff_posterize_rowB_0_address0;
output   image_diff_posterize_rowB_0_ce0;
input  [7:0] image_diff_posterize_rowB_0_q0;
output  [4:0] image_diff_posterize_rowB_1_address0;
output   image_diff_posterize_rowB_1_ce0;
input  [7:0] image_diff_posterize_rowB_1_q0;
output  [4:0] image_diff_posterize_rowB_2_address0;
output   image_diff_posterize_rowB_2_ce0;
input  [7:0] image_diff_posterize_rowB_2_q0;
output  [4:0] image_diff_posterize_rowB_3_address0;
output   image_diff_posterize_rowB_3_ce0;
input  [7:0] image_diff_posterize_rowB_3_q0;
output  [4:0] image_diff_posterize_rowB_4_address0;
output   image_diff_posterize_rowB_4_ce0;
input  [7:0] image_diff_posterize_rowB_4_q0;
output  [4:0] image_diff_posterize_rowB_5_address0;
output   image_diff_posterize_rowB_5_ce0;
input  [7:0] image_diff_posterize_rowB_5_q0;
output  [4:0] image_diff_posterize_rowB_6_address0;
output   image_diff_posterize_rowB_6_ce0;
input  [7:0] image_diff_posterize_rowB_6_q0;
output  [4:0] image_diff_posterize_rowB_7_address0;
output   image_diff_posterize_rowB_7_ce0;
input  [7:0] image_diff_posterize_rowB_7_q0;
output  [4:0] image_diff_posterize_rowC_0_address0;
output   image_diff_posterize_rowC_0_ce0;
output   image_diff_posterize_rowC_0_we0;
output  [7:0] image_diff_posterize_rowC_0_d0;
output  [4:0] image_diff_posterize_rowC_1_address0;
output   image_diff_posterize_rowC_1_ce0;
output   image_diff_posterize_rowC_1_we0;
output  [7:0] image_diff_posterize_rowC_1_d0;
output  [4:0] image_diff_posterize_rowC_2_address0;
output   image_diff_posterize_rowC_2_ce0;
output   image_diff_posterize_rowC_2_we0;
output  [7:0] image_diff_posterize_rowC_2_d0;
output  [4:0] image_diff_posterize_rowC_3_address0;
output   image_diff_posterize_rowC_3_ce0;
output   image_diff_posterize_rowC_3_we0;
output  [7:0] image_diff_posterize_rowC_3_d0;
output  [4:0] image_diff_posterize_rowC_4_address0;
output   image_diff_posterize_rowC_4_ce0;
output   image_diff_posterize_rowC_4_we0;
output  [7:0] image_diff_posterize_rowC_4_d0;
output  [4:0] image_diff_posterize_rowC_5_address0;
output   image_diff_posterize_rowC_5_ce0;
output   image_diff_posterize_rowC_5_we0;
output  [7:0] image_diff_posterize_rowC_5_d0;
output  [4:0] image_diff_posterize_rowC_6_address0;
output   image_diff_posterize_rowC_6_ce0;
output   image_diff_posterize_rowC_6_we0;
output  [7:0] image_diff_posterize_rowC_6_d0;
output  [4:0] image_diff_posterize_rowC_7_address0;
output   image_diff_posterize_rowC_7_ce0;
output   image_diff_posterize_rowC_7_we0;
output  [7:0] image_diff_posterize_rowC_7_d0;

reg ap_idle;
reg image_diff_posterize_rowA_0_ce0;
reg image_diff_posterize_rowA_1_ce0;
reg image_diff_posterize_rowA_2_ce0;
reg image_diff_posterize_rowA_3_ce0;
reg image_diff_posterize_rowA_4_ce0;
reg image_diff_posterize_rowA_5_ce0;
reg image_diff_posterize_rowA_6_ce0;
reg image_diff_posterize_rowA_7_ce0;
reg image_diff_posterize_rowB_0_ce0;
reg image_diff_posterize_rowB_1_ce0;
reg image_diff_posterize_rowB_2_ce0;
reg image_diff_posterize_rowB_3_ce0;
reg image_diff_posterize_rowB_4_ce0;
reg image_diff_posterize_rowB_5_ce0;
reg image_diff_posterize_rowB_6_ce0;
reg image_diff_posterize_rowB_7_ce0;
reg image_diff_posterize_rowC_0_ce0;
reg image_diff_posterize_rowC_0_we0;
reg image_diff_posterize_rowC_1_ce0;
reg image_diff_posterize_rowC_1_we0;
reg image_diff_posterize_rowC_2_ce0;
reg image_diff_posterize_rowC_2_we0;
reg image_diff_posterize_rowC_3_ce0;
reg image_diff_posterize_rowC_3_we0;
reg image_diff_posterize_rowC_4_ce0;
reg image_diff_posterize_rowC_4_we0;
reg image_diff_posterize_rowC_5_ce0;
reg image_diff_posterize_rowC_5_we0;
reg image_diff_posterize_rowC_6_ce0;
reg image_diff_posterize_rowC_6_we0;
reg image_diff_posterize_rowC_7_ce0;
reg image_diff_posterize_rowC_7_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] tmp_fu_418_p3;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [63:0] zext_ln81_fu_436_p1;
reg   [63:0] zext_ln81_reg_1109;
reg    ap_block_pp0_stage0_11001;
wire    ap_block_pp0_stage0;
reg   [8:0] j_fu_94;
wire   [8:0] add_ln76_fu_456_p2;
wire    ap_loop_init;
reg   [8:0] ap_sig_allocacmp_j_3;
wire   [4:0] lshr_ln_fu_426_p4;
wire   [8:0] zext_ln81_1_fu_467_p1;
wire   [8:0] zext_ln81_2_fu_471_p1;
wire   [8:0] diff_temp_fu_475_p2;
wire   [7:0] trunc_ln84_fu_481_p1;
wire   [0:0] tmp_1_fu_485_p3;
wire   [7:0] sub_ln84_fu_493_p2;
wire   [7:0] diff_fu_499_p3;
wire   [2:0] tmp_2_fu_507_p4;
wire   [0:0] icmp_ln86_fu_517_p2;
wire   [0:0] icmp_ln87_fu_523_p2;
wire   [7:0] select_ln86_fu_529_p3;
wire   [8:0] zext_ln81_3_fu_546_p1;
wire   [8:0] zext_ln81_4_fu_550_p1;
wire   [8:0] diff_temp_1_fu_554_p2;
wire   [7:0] trunc_ln84_1_fu_560_p1;
wire   [0:0] tmp_3_fu_564_p3;
wire   [7:0] sub_ln84_1_fu_572_p2;
wire   [7:0] diff_1_fu_578_p3;
wire   [2:0] tmp_4_fu_586_p4;
wire   [0:0] icmp_ln86_1_fu_596_p2;
wire   [0:0] icmp_ln87_1_fu_602_p2;
wire   [7:0] select_ln86_2_fu_608_p3;
wire   [8:0] zext_ln81_5_fu_625_p1;
wire   [8:0] zext_ln81_6_fu_629_p1;
wire   [8:0] diff_temp_2_fu_633_p2;
wire   [7:0] trunc_ln84_2_fu_639_p1;
wire   [0:0] tmp_5_fu_643_p3;
wire   [7:0] sub_ln84_2_fu_651_p2;
wire   [7:0] diff_2_fu_657_p3;
wire   [2:0] tmp_6_fu_665_p4;
wire   [0:0] icmp_ln86_2_fu_675_p2;
wire   [0:0] icmp_ln87_2_fu_681_p2;
wire   [7:0] select_ln86_4_fu_687_p3;
wire   [8:0] zext_ln81_7_fu_704_p1;
wire   [8:0] zext_ln81_8_fu_708_p1;
wire   [8:0] diff_temp_3_fu_712_p2;
wire   [7:0] trunc_ln84_3_fu_718_p1;
wire   [0:0] tmp_7_fu_722_p3;
wire   [7:0] sub_ln84_3_fu_730_p2;
wire   [7:0] diff_3_fu_736_p3;
wire   [2:0] tmp_8_fu_744_p4;
wire   [0:0] icmp_ln86_3_fu_754_p2;
wire   [0:0] icmp_ln87_3_fu_760_p2;
wire   [7:0] select_ln86_6_fu_766_p3;
wire   [8:0] zext_ln81_9_fu_783_p1;
wire   [8:0] zext_ln81_10_fu_787_p1;
wire   [8:0] diff_temp_4_fu_791_p2;
wire   [7:0] trunc_ln84_4_fu_797_p1;
wire   [0:0] tmp_9_fu_801_p3;
wire   [7:0] sub_ln84_4_fu_809_p2;
wire   [7:0] diff_4_fu_815_p3;
wire   [2:0] tmp_10_fu_823_p4;
wire   [0:0] icmp_ln86_4_fu_833_p2;
wire   [0:0] icmp_ln87_4_fu_839_p2;
wire   [7:0] select_ln86_8_fu_845_p3;
wire   [8:0] zext_ln81_11_fu_862_p1;
wire   [8:0] zext_ln81_12_fu_866_p1;
wire   [8:0] diff_temp_5_fu_870_p2;
wire   [7:0] trunc_ln84_5_fu_876_p1;
wire   [0:0] tmp_11_fu_880_p3;
wire   [7:0] sub_ln84_5_fu_888_p2;
wire   [7:0] diff_5_fu_894_p3;
wire   [2:0] tmp_12_fu_902_p4;
wire   [0:0] icmp_ln86_5_fu_912_p2;
wire   [0:0] icmp_ln87_5_fu_918_p2;
wire   [7:0] select_ln86_10_fu_924_p3;
wire   [8:0] zext_ln81_13_fu_941_p1;
wire   [8:0] zext_ln81_14_fu_945_p1;
wire   [8:0] diff_temp_6_fu_949_p2;
wire   [7:0] trunc_ln84_6_fu_955_p1;
wire   [0:0] tmp_13_fu_959_p3;
wire   [7:0] sub_ln84_6_fu_967_p2;
wire   [7:0] diff_6_fu_973_p3;
wire   [2:0] tmp_14_fu_981_p4;
wire   [0:0] icmp_ln86_6_fu_991_p2;
wire   [0:0] icmp_ln87_6_fu_997_p2;
wire   [7:0] select_ln86_12_fu_1003_p3;
wire   [8:0] zext_ln81_15_fu_1020_p1;
wire   [8:0] zext_ln81_16_fu_1024_p1;
wire   [8:0] diff_temp_7_fu_1028_p2;
wire   [7:0] trunc_ln84_7_fu_1034_p1;
wire   [0:0] tmp_15_fu_1038_p3;
wire   [7:0] sub_ln84_7_fu_1046_p2;
wire   [7:0] diff_7_fu_1052_p3;
wire   [2:0] tmp_16_fu_1060_p4;
wire   [0:0] icmp_ln86_7_fu_1070_p2;
wire   [0:0] icmp_ln87_7_fu_1076_p2;
wire   [7:0] select_ln86_14_fu_1082_p3;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_268;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

image_diff_posterize_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_268)) begin
        if ((tmp_fu_418_p3 == 1'd0)) begin
            j_fu_94 <= add_ln76_fu_456_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_94 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_fu_418_p3 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        zext_ln81_reg_1109[4 : 0] <= zext_ln81_fu_436_p1[4 : 0];
    end
end

always @ (*) begin
    if (((tmp_fu_418_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j_3 = 9'd0;
    end else begin
        ap_sig_allocacmp_j_3 = j_fu_94;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        image_diff_posterize_rowA_0_ce0 = 1'b1;
    end else begin
        image_diff_posterize_rowA_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        image_diff_posterize_rowA_1_ce0 = 1'b1;
    end else begin
        image_diff_posterize_rowA_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        image_diff_posterize_rowA_2_ce0 = 1'b1;
    end else begin
        image_diff_posterize_rowA_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        image_diff_posterize_rowA_3_ce0 = 1'b1;
    end else begin
        image_diff_posterize_rowA_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        image_diff_posterize_rowA_4_ce0 = 1'b1;
    end else begin
        image_diff_posterize_rowA_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        image_diff_posterize_rowA_5_ce0 = 1'b1;
    end else begin
        image_diff_posterize_rowA_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        image_diff_posterize_rowA_6_ce0 = 1'b1;
    end else begin
        image_diff_posterize_rowA_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        image_diff_posterize_rowA_7_ce0 = 1'b1;
    end else begin
        image_diff_posterize_rowA_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        image_diff_posterize_rowB_0_ce0 = 1'b1;
    end else begin
        image_diff_posterize_rowB_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        image_diff_posterize_rowB_1_ce0 = 1'b1;
    end else begin
        image_diff_posterize_rowB_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        image_diff_posterize_rowB_2_ce0 = 1'b1;
    end else begin
        image_diff_posterize_rowB_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        image_diff_posterize_rowB_3_ce0 = 1'b1;
    end else begin
        image_diff_posterize_rowB_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        image_diff_posterize_rowB_4_ce0 = 1'b1;
    end else begin
        image_diff_posterize_rowB_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        image_diff_posterize_rowB_5_ce0 = 1'b1;
    end else begin
        image_diff_posterize_rowB_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        image_diff_posterize_rowB_6_ce0 = 1'b1;
    end else begin
        image_diff_posterize_rowB_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        image_diff_posterize_rowB_7_ce0 = 1'b1;
    end else begin
        image_diff_posterize_rowB_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        image_diff_posterize_rowC_0_ce0 = 1'b1;
    end else begin
        image_diff_posterize_rowC_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        image_diff_posterize_rowC_0_we0 = 1'b1;
    end else begin
        image_diff_posterize_rowC_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        image_diff_posterize_rowC_1_ce0 = 1'b1;
    end else begin
        image_diff_posterize_rowC_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        image_diff_posterize_rowC_1_we0 = 1'b1;
    end else begin
        image_diff_posterize_rowC_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        image_diff_posterize_rowC_2_ce0 = 1'b1;
    end else begin
        image_diff_posterize_rowC_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        image_diff_posterize_rowC_2_we0 = 1'b1;
    end else begin
        image_diff_posterize_rowC_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        image_diff_posterize_rowC_3_ce0 = 1'b1;
    end else begin
        image_diff_posterize_rowC_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        image_diff_posterize_rowC_3_we0 = 1'b1;
    end else begin
        image_diff_posterize_rowC_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        image_diff_posterize_rowC_4_ce0 = 1'b1;
    end else begin
        image_diff_posterize_rowC_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        image_diff_posterize_rowC_4_we0 = 1'b1;
    end else begin
        image_diff_posterize_rowC_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        image_diff_posterize_rowC_5_ce0 = 1'b1;
    end else begin
        image_diff_posterize_rowC_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        image_diff_posterize_rowC_5_we0 = 1'b1;
    end else begin
        image_diff_posterize_rowC_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        image_diff_posterize_rowC_6_ce0 = 1'b1;
    end else begin
        image_diff_posterize_rowC_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        image_diff_posterize_rowC_6_we0 = 1'b1;
    end else begin
        image_diff_posterize_rowC_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        image_diff_posterize_rowC_7_ce0 = 1'b1;
    end else begin
        image_diff_posterize_rowC_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        image_diff_posterize_rowC_7_we0 = 1'b1;
    end else begin
        image_diff_posterize_rowC_7_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln76_fu_456_p2 = (ap_sig_allocacmp_j_3 + 9'd8);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_268 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign diff_1_fu_578_p3 = ((tmp_3_fu_564_p3[0:0] == 1'b1) ? sub_ln84_1_fu_572_p2 : trunc_ln84_1_fu_560_p1);

assign diff_2_fu_657_p3 = ((tmp_5_fu_643_p3[0:0] == 1'b1) ? sub_ln84_2_fu_651_p2 : trunc_ln84_2_fu_639_p1);

assign diff_3_fu_736_p3 = ((tmp_7_fu_722_p3[0:0] == 1'b1) ? sub_ln84_3_fu_730_p2 : trunc_ln84_3_fu_718_p1);

assign diff_4_fu_815_p3 = ((tmp_9_fu_801_p3[0:0] == 1'b1) ? sub_ln84_4_fu_809_p2 : trunc_ln84_4_fu_797_p1);

assign diff_5_fu_894_p3 = ((tmp_11_fu_880_p3[0:0] == 1'b1) ? sub_ln84_5_fu_888_p2 : trunc_ln84_5_fu_876_p1);

assign diff_6_fu_973_p3 = ((tmp_13_fu_959_p3[0:0] == 1'b1) ? sub_ln84_6_fu_967_p2 : trunc_ln84_6_fu_955_p1);

assign diff_7_fu_1052_p3 = ((tmp_15_fu_1038_p3[0:0] == 1'b1) ? sub_ln84_7_fu_1046_p2 : trunc_ln84_7_fu_1034_p1);

assign diff_fu_499_p3 = ((tmp_1_fu_485_p3[0:0] == 1'b1) ? sub_ln84_fu_493_p2 : trunc_ln84_fu_481_p1);

assign diff_temp_1_fu_554_p2 = (zext_ln81_3_fu_546_p1 - zext_ln81_4_fu_550_p1);

assign diff_temp_2_fu_633_p2 = (zext_ln81_5_fu_625_p1 - zext_ln81_6_fu_629_p1);

assign diff_temp_3_fu_712_p2 = (zext_ln81_7_fu_704_p1 - zext_ln81_8_fu_708_p1);

assign diff_temp_4_fu_791_p2 = (zext_ln81_9_fu_783_p1 - zext_ln81_10_fu_787_p1);

assign diff_temp_5_fu_870_p2 = (zext_ln81_11_fu_862_p1 - zext_ln81_12_fu_866_p1);

assign diff_temp_6_fu_949_p2 = (zext_ln81_13_fu_941_p1 - zext_ln81_14_fu_945_p1);

assign diff_temp_7_fu_1028_p2 = (zext_ln81_15_fu_1020_p1 - zext_ln81_16_fu_1024_p1);

assign diff_temp_fu_475_p2 = (zext_ln81_1_fu_467_p1 - zext_ln81_2_fu_471_p1);

assign icmp_ln86_1_fu_596_p2 = ((tmp_4_fu_586_p4 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln86_2_fu_675_p2 = ((tmp_6_fu_665_p4 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln86_3_fu_754_p2 = ((tmp_8_fu_744_p4 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln86_4_fu_833_p2 = ((tmp_10_fu_823_p4 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln86_5_fu_912_p2 = ((tmp_12_fu_902_p4 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln86_6_fu_991_p2 = ((tmp_14_fu_981_p4 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln86_7_fu_1070_p2 = ((tmp_16_fu_1060_p4 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln86_fu_517_p2 = ((tmp_2_fu_507_p4 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln87_1_fu_602_p2 = ((diff_1_fu_578_p3 < 8'd96) ? 1'b1 : 1'b0);

assign icmp_ln87_2_fu_681_p2 = ((diff_2_fu_657_p3 < 8'd96) ? 1'b1 : 1'b0);

assign icmp_ln87_3_fu_760_p2 = ((diff_3_fu_736_p3 < 8'd96) ? 1'b1 : 1'b0);

assign icmp_ln87_4_fu_839_p2 = ((diff_4_fu_815_p3 < 8'd96) ? 1'b1 : 1'b0);

assign icmp_ln87_5_fu_918_p2 = ((diff_5_fu_894_p3 < 8'd96) ? 1'b1 : 1'b0);

assign icmp_ln87_6_fu_997_p2 = ((diff_6_fu_973_p3 < 8'd96) ? 1'b1 : 1'b0);

assign icmp_ln87_7_fu_1076_p2 = ((diff_7_fu_1052_p3 < 8'd96) ? 1'b1 : 1'b0);

assign icmp_ln87_fu_523_p2 = ((diff_fu_499_p3 < 8'd96) ? 1'b1 : 1'b0);

assign image_diff_posterize_rowA_0_address0 = zext_ln81_fu_436_p1;

assign image_diff_posterize_rowA_1_address0 = zext_ln81_fu_436_p1;

assign image_diff_posterize_rowA_2_address0 = zext_ln81_fu_436_p1;

assign image_diff_posterize_rowA_3_address0 = zext_ln81_fu_436_p1;

assign image_diff_posterize_rowA_4_address0 = zext_ln81_fu_436_p1;

assign image_diff_posterize_rowA_5_address0 = zext_ln81_fu_436_p1;

assign image_diff_posterize_rowA_6_address0 = zext_ln81_fu_436_p1;

assign image_diff_posterize_rowA_7_address0 = zext_ln81_fu_436_p1;

assign image_diff_posterize_rowB_0_address0 = zext_ln81_fu_436_p1;

assign image_diff_posterize_rowB_1_address0 = zext_ln81_fu_436_p1;

assign image_diff_posterize_rowB_2_address0 = zext_ln81_fu_436_p1;

assign image_diff_posterize_rowB_3_address0 = zext_ln81_fu_436_p1;

assign image_diff_posterize_rowB_4_address0 = zext_ln81_fu_436_p1;

assign image_diff_posterize_rowB_5_address0 = zext_ln81_fu_436_p1;

assign image_diff_posterize_rowB_6_address0 = zext_ln81_fu_436_p1;

assign image_diff_posterize_rowB_7_address0 = zext_ln81_fu_436_p1;

assign image_diff_posterize_rowC_0_address0 = zext_ln81_reg_1109;

assign image_diff_posterize_rowC_0_d0 = ((icmp_ln87_fu_523_p2[0:0] == 1'b1) ? select_ln86_fu_529_p3 : 8'd255);

assign image_diff_posterize_rowC_1_address0 = zext_ln81_reg_1109;

assign image_diff_posterize_rowC_1_d0 = ((icmp_ln87_1_fu_602_p2[0:0] == 1'b1) ? select_ln86_2_fu_608_p3 : 8'd255);

assign image_diff_posterize_rowC_2_address0 = zext_ln81_reg_1109;

assign image_diff_posterize_rowC_2_d0 = ((icmp_ln87_2_fu_681_p2[0:0] == 1'b1) ? select_ln86_4_fu_687_p3 : 8'd255);

assign image_diff_posterize_rowC_3_address0 = zext_ln81_reg_1109;

assign image_diff_posterize_rowC_3_d0 = ((icmp_ln87_3_fu_760_p2[0:0] == 1'b1) ? select_ln86_6_fu_766_p3 : 8'd255);

assign image_diff_posterize_rowC_4_address0 = zext_ln81_reg_1109;

assign image_diff_posterize_rowC_4_d0 = ((icmp_ln87_4_fu_839_p2[0:0] == 1'b1) ? select_ln86_8_fu_845_p3 : 8'd255);

assign image_diff_posterize_rowC_5_address0 = zext_ln81_reg_1109;

assign image_diff_posterize_rowC_5_d0 = ((icmp_ln87_5_fu_918_p2[0:0] == 1'b1) ? select_ln86_10_fu_924_p3 : 8'd255);

assign image_diff_posterize_rowC_6_address0 = zext_ln81_reg_1109;

assign image_diff_posterize_rowC_6_d0 = ((icmp_ln87_6_fu_997_p2[0:0] == 1'b1) ? select_ln86_12_fu_1003_p3 : 8'd255);

assign image_diff_posterize_rowC_7_address0 = zext_ln81_reg_1109;

assign image_diff_posterize_rowC_7_d0 = ((icmp_ln87_7_fu_1076_p2[0:0] == 1'b1) ? select_ln86_14_fu_1082_p3 : 8'd255);

assign lshr_ln_fu_426_p4 = {{ap_sig_allocacmp_j_3[7:3]}};

assign select_ln86_10_fu_924_p3 = ((icmp_ln86_5_fu_912_p2[0:0] == 1'b1) ? 8'd0 : 8'd128);

assign select_ln86_12_fu_1003_p3 = ((icmp_ln86_6_fu_991_p2[0:0] == 1'b1) ? 8'd0 : 8'd128);

assign select_ln86_14_fu_1082_p3 = ((icmp_ln86_7_fu_1070_p2[0:0] == 1'b1) ? 8'd0 : 8'd128);

assign select_ln86_2_fu_608_p3 = ((icmp_ln86_1_fu_596_p2[0:0] == 1'b1) ? 8'd0 : 8'd128);

assign select_ln86_4_fu_687_p3 = ((icmp_ln86_2_fu_675_p2[0:0] == 1'b1) ? 8'd0 : 8'd128);

assign select_ln86_6_fu_766_p3 = ((icmp_ln86_3_fu_754_p2[0:0] == 1'b1) ? 8'd0 : 8'd128);

assign select_ln86_8_fu_845_p3 = ((icmp_ln86_4_fu_833_p2[0:0] == 1'b1) ? 8'd0 : 8'd128);

assign select_ln86_fu_529_p3 = ((icmp_ln86_fu_517_p2[0:0] == 1'b1) ? 8'd0 : 8'd128);

assign sub_ln84_1_fu_572_p2 = (8'd0 - trunc_ln84_1_fu_560_p1);

assign sub_ln84_2_fu_651_p2 = (8'd0 - trunc_ln84_2_fu_639_p1);

assign sub_ln84_3_fu_730_p2 = (8'd0 - trunc_ln84_3_fu_718_p1);

assign sub_ln84_4_fu_809_p2 = (8'd0 - trunc_ln84_4_fu_797_p1);

assign sub_ln84_5_fu_888_p2 = (8'd0 - trunc_ln84_5_fu_876_p1);

assign sub_ln84_6_fu_967_p2 = (8'd0 - trunc_ln84_6_fu_955_p1);

assign sub_ln84_7_fu_1046_p2 = (8'd0 - trunc_ln84_7_fu_1034_p1);

assign sub_ln84_fu_493_p2 = (8'd0 - trunc_ln84_fu_481_p1);

assign tmp_10_fu_823_p4 = {{diff_4_fu_815_p3[7:5]}};

assign tmp_11_fu_880_p3 = diff_temp_5_fu_870_p2[32'd8];

assign tmp_12_fu_902_p4 = {{diff_5_fu_894_p3[7:5]}};

assign tmp_13_fu_959_p3 = diff_temp_6_fu_949_p2[32'd8];

assign tmp_14_fu_981_p4 = {{diff_6_fu_973_p3[7:5]}};

assign tmp_15_fu_1038_p3 = diff_temp_7_fu_1028_p2[32'd8];

assign tmp_16_fu_1060_p4 = {{diff_7_fu_1052_p3[7:5]}};

assign tmp_1_fu_485_p3 = diff_temp_fu_475_p2[32'd8];

assign tmp_2_fu_507_p4 = {{diff_fu_499_p3[7:5]}};

assign tmp_3_fu_564_p3 = diff_temp_1_fu_554_p2[32'd8];

assign tmp_4_fu_586_p4 = {{diff_1_fu_578_p3[7:5]}};

assign tmp_5_fu_643_p3 = diff_temp_2_fu_633_p2[32'd8];

assign tmp_6_fu_665_p4 = {{diff_2_fu_657_p3[7:5]}};

assign tmp_7_fu_722_p3 = diff_temp_3_fu_712_p2[32'd8];

assign tmp_8_fu_744_p4 = {{diff_3_fu_736_p3[7:5]}};

assign tmp_9_fu_801_p3 = diff_temp_4_fu_791_p2[32'd8];

assign tmp_fu_418_p3 = ap_sig_allocacmp_j_3[32'd8];

assign trunc_ln84_1_fu_560_p1 = diff_temp_1_fu_554_p2[7:0];

assign trunc_ln84_2_fu_639_p1 = diff_temp_2_fu_633_p2[7:0];

assign trunc_ln84_3_fu_718_p1 = diff_temp_3_fu_712_p2[7:0];

assign trunc_ln84_4_fu_797_p1 = diff_temp_4_fu_791_p2[7:0];

assign trunc_ln84_5_fu_876_p1 = diff_temp_5_fu_870_p2[7:0];

assign trunc_ln84_6_fu_955_p1 = diff_temp_6_fu_949_p2[7:0];

assign trunc_ln84_7_fu_1034_p1 = diff_temp_7_fu_1028_p2[7:0];

assign trunc_ln84_fu_481_p1 = diff_temp_fu_475_p2[7:0];

assign zext_ln81_10_fu_787_p1 = image_diff_posterize_rowB_4_q0;

assign zext_ln81_11_fu_862_p1 = image_diff_posterize_rowA_5_q0;

assign zext_ln81_12_fu_866_p1 = image_diff_posterize_rowB_5_q0;

assign zext_ln81_13_fu_941_p1 = image_diff_posterize_rowA_6_q0;

assign zext_ln81_14_fu_945_p1 = image_diff_posterize_rowB_6_q0;

assign zext_ln81_15_fu_1020_p1 = image_diff_posterize_rowA_7_q0;

assign zext_ln81_16_fu_1024_p1 = image_diff_posterize_rowB_7_q0;

assign zext_ln81_1_fu_467_p1 = image_diff_posterize_rowA_0_q0;

assign zext_ln81_2_fu_471_p1 = image_diff_posterize_rowB_0_q0;

assign zext_ln81_3_fu_546_p1 = image_diff_posterize_rowA_1_q0;

assign zext_ln81_4_fu_550_p1 = image_diff_posterize_rowB_1_q0;

assign zext_ln81_5_fu_625_p1 = image_diff_posterize_rowA_2_q0;

assign zext_ln81_6_fu_629_p1 = image_diff_posterize_rowB_2_q0;

assign zext_ln81_7_fu_704_p1 = image_diff_posterize_rowA_3_q0;

assign zext_ln81_8_fu_708_p1 = image_diff_posterize_rowB_3_q0;

assign zext_ln81_9_fu_783_p1 = image_diff_posterize_rowA_4_q0;

assign zext_ln81_fu_436_p1 = lshr_ln_fu_426_p4;

always @ (posedge ap_clk) begin
    zext_ln81_reg_1109[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
end

endmodule //image_diff_posterize_Col_Loop_proc
