// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module image_diff_posterize_Read_Loop_proc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RFIFONUM,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        i,
        A,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RFIFONUM,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        B,
        image_diff_posterize_rowA_0_address0,
        image_diff_posterize_rowA_0_ce0,
        image_diff_posterize_rowA_0_we0,
        image_diff_posterize_rowA_0_d0,
        image_diff_posterize_rowB_0_address0,
        image_diff_posterize_rowB_0_ce0,
        image_diff_posterize_rowB_0_we0,
        image_diff_posterize_rowB_0_d0,
        image_diff_posterize_rowA_1_address0,
        image_diff_posterize_rowA_1_ce0,
        image_diff_posterize_rowA_1_we0,
        image_diff_posterize_rowA_1_d0,
        image_diff_posterize_rowB_1_address0,
        image_diff_posterize_rowB_1_ce0,
        image_diff_posterize_rowB_1_we0,
        image_diff_posterize_rowB_1_d0,
        image_diff_posterize_rowA_2_address0,
        image_diff_posterize_rowA_2_ce0,
        image_diff_posterize_rowA_2_we0,
        image_diff_posterize_rowA_2_d0,
        image_diff_posterize_rowB_2_address0,
        image_diff_posterize_rowB_2_ce0,
        image_diff_posterize_rowB_2_we0,
        image_diff_posterize_rowB_2_d0,
        image_diff_posterize_rowA_3_address0,
        image_diff_posterize_rowA_3_ce0,
        image_diff_posterize_rowA_3_we0,
        image_diff_posterize_rowA_3_d0,
        image_diff_posterize_rowB_3_address0,
        image_diff_posterize_rowB_3_ce0,
        image_diff_posterize_rowB_3_we0,
        image_diff_posterize_rowB_3_d0,
        image_diff_posterize_rowA_4_address0,
        image_diff_posterize_rowA_4_ce0,
        image_diff_posterize_rowA_4_we0,
        image_diff_posterize_rowA_4_d0,
        image_diff_posterize_rowB_4_address0,
        image_diff_posterize_rowB_4_ce0,
        image_diff_posterize_rowB_4_we0,
        image_diff_posterize_rowB_4_d0,
        image_diff_posterize_rowA_5_address0,
        image_diff_posterize_rowA_5_ce0,
        image_diff_posterize_rowA_5_we0,
        image_diff_posterize_rowA_5_d0,
        image_diff_posterize_rowB_5_address0,
        image_diff_posterize_rowB_5_ce0,
        image_diff_posterize_rowB_5_we0,
        image_diff_posterize_rowB_5_d0,
        image_diff_posterize_rowA_6_address0,
        image_diff_posterize_rowA_6_ce0,
        image_diff_posterize_rowA_6_we0,
        image_diff_posterize_rowA_6_d0,
        image_diff_posterize_rowB_6_address0,
        image_diff_posterize_rowB_6_ce0,
        image_diff_posterize_rowB_6_we0,
        image_diff_posterize_rowB_6_d0,
        image_diff_posterize_rowA_7_address0,
        image_diff_posterize_rowA_7_ce0,
        image_diff_posterize_rowA_7_we0,
        image_diff_posterize_rowA_7_d0,
        image_diff_posterize_rowB_7_address0,
        image_diff_posterize_rowB_7_ce0,
        image_diff_posterize_rowB_7_we0,
        image_diff_posterize_rowB_7_d0,
        ap_return
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_state4 = 10'd8;
parameter    ap_ST_fsm_state5 = 10'd16;
parameter    ap_ST_fsm_state6 = 10'd32;
parameter    ap_ST_fsm_state7 = 10'd64;
parameter    ap_ST_fsm_state8 = 10'd128;
parameter    ap_ST_fsm_state9 = 10'd256;
parameter    ap_ST_fsm_state10 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [63:0] m_axi_gmem0_AWADDR;
output  [0:0] m_axi_gmem0_AWID;
output  [31:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [0:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [7:0] m_axi_gmem0_WDATA;
output  [0:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [0:0] m_axi_gmem0_WID;
output  [0:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [63:0] m_axi_gmem0_ARADDR;
output  [0:0] m_axi_gmem0_ARID;
output  [31:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [0:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [7:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [0:0] m_axi_gmem0_RID;
input  [10:0] m_axi_gmem0_RFIFONUM;
input  [0:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [0:0] m_axi_gmem0_BID;
input  [0:0] m_axi_gmem0_BUSER;
input  [7:0] i;
input  [63:0] A;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [63:0] m_axi_gmem1_AWADDR;
output  [0:0] m_axi_gmem1_AWID;
output  [31:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [0:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [7:0] m_axi_gmem1_WDATA;
output  [0:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [0:0] m_axi_gmem1_WID;
output  [0:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [63:0] m_axi_gmem1_ARADDR;
output  [0:0] m_axi_gmem1_ARID;
output  [31:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [0:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [7:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [0:0] m_axi_gmem1_RID;
input  [10:0] m_axi_gmem1_RFIFONUM;
input  [0:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [0:0] m_axi_gmem1_BID;
input  [0:0] m_axi_gmem1_BUSER;
input  [63:0] B;
output  [4:0] image_diff_posterize_rowA_0_address0;
output   image_diff_posterize_rowA_0_ce0;
output   image_diff_posterize_rowA_0_we0;
output  [7:0] image_diff_posterize_rowA_0_d0;
output  [4:0] image_diff_posterize_rowB_0_address0;
output   image_diff_posterize_rowB_0_ce0;
output   image_diff_posterize_rowB_0_we0;
output  [7:0] image_diff_posterize_rowB_0_d0;
output  [4:0] image_diff_posterize_rowA_1_address0;
output   image_diff_posterize_rowA_1_ce0;
output   image_diff_posterize_rowA_1_we0;
output  [7:0] image_diff_posterize_rowA_1_d0;
output  [4:0] image_diff_posterize_rowB_1_address0;
output   image_diff_posterize_rowB_1_ce0;
output   image_diff_posterize_rowB_1_we0;
output  [7:0] image_diff_posterize_rowB_1_d0;
output  [4:0] image_diff_posterize_rowA_2_address0;
output   image_diff_posterize_rowA_2_ce0;
output   image_diff_posterize_rowA_2_we0;
output  [7:0] image_diff_posterize_rowA_2_d0;
output  [4:0] image_diff_posterize_rowB_2_address0;
output   image_diff_posterize_rowB_2_ce0;
output   image_diff_posterize_rowB_2_we0;
output  [7:0] image_diff_posterize_rowB_2_d0;
output  [4:0] image_diff_posterize_rowA_3_address0;
output   image_diff_posterize_rowA_3_ce0;
output   image_diff_posterize_rowA_3_we0;
output  [7:0] image_diff_posterize_rowA_3_d0;
output  [4:0] image_diff_posterize_rowB_3_address0;
output   image_diff_posterize_rowB_3_ce0;
output   image_diff_posterize_rowB_3_we0;
output  [7:0] image_diff_posterize_rowB_3_d0;
output  [4:0] image_diff_posterize_rowA_4_address0;
output   image_diff_posterize_rowA_4_ce0;
output   image_diff_posterize_rowA_4_we0;
output  [7:0] image_diff_posterize_rowA_4_d0;
output  [4:0] image_diff_posterize_rowB_4_address0;
output   image_diff_posterize_rowB_4_ce0;
output   image_diff_posterize_rowB_4_we0;
output  [7:0] image_diff_posterize_rowB_4_d0;
output  [4:0] image_diff_posterize_rowA_5_address0;
output   image_diff_posterize_rowA_5_ce0;
output   image_diff_posterize_rowA_5_we0;
output  [7:0] image_diff_posterize_rowA_5_d0;
output  [4:0] image_diff_posterize_rowB_5_address0;
output   image_diff_posterize_rowB_5_ce0;
output   image_diff_posterize_rowB_5_we0;
output  [7:0] image_diff_posterize_rowB_5_d0;
output  [4:0] image_diff_posterize_rowA_6_address0;
output   image_diff_posterize_rowA_6_ce0;
output   image_diff_posterize_rowA_6_we0;
output  [7:0] image_diff_posterize_rowA_6_d0;
output  [4:0] image_diff_posterize_rowB_6_address0;
output   image_diff_posterize_rowB_6_ce0;
output   image_diff_posterize_rowB_6_we0;
output  [7:0] image_diff_posterize_rowB_6_d0;
output  [4:0] image_diff_posterize_rowA_7_address0;
output   image_diff_posterize_rowA_7_ce0;
output   image_diff_posterize_rowA_7_we0;
output  [7:0] image_diff_posterize_rowA_7_d0;
output  [4:0] image_diff_posterize_rowB_7_address0;
output   image_diff_posterize_rowB_7_ce0;
output   image_diff_posterize_rowB_7_we0;
output  [7:0] image_diff_posterize_rowB_7_d0;
output  [7:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg m_axi_gmem0_ARVALID;
reg[63:0] m_axi_gmem0_ARADDR;
reg[0:0] m_axi_gmem0_ARID;
reg[31:0] m_axi_gmem0_ARLEN;
reg[2:0] m_axi_gmem0_ARSIZE;
reg[1:0] m_axi_gmem0_ARBURST;
reg[1:0] m_axi_gmem0_ARLOCK;
reg[3:0] m_axi_gmem0_ARCACHE;
reg[2:0] m_axi_gmem0_ARPROT;
reg[3:0] m_axi_gmem0_ARQOS;
reg[3:0] m_axi_gmem0_ARREGION;
reg[0:0] m_axi_gmem0_ARUSER;
reg m_axi_gmem0_RREADY;
reg m_axi_gmem1_ARVALID;
reg[63:0] m_axi_gmem1_ARADDR;
reg[0:0] m_axi_gmem1_ARID;
reg[31:0] m_axi_gmem1_ARLEN;
reg[2:0] m_axi_gmem1_ARSIZE;
reg[1:0] m_axi_gmem1_ARBURST;
reg[1:0] m_axi_gmem1_ARLOCK;
reg[3:0] m_axi_gmem1_ARCACHE;
reg[2:0] m_axi_gmem1_ARPROT;
reg[3:0] m_axi_gmem1_ARQOS;
reg[3:0] m_axi_gmem1_ARREGION;
reg[0:0] m_axi_gmem1_ARUSER;
reg m_axi_gmem1_RREADY;
reg[7:0] ap_return;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    gmem0_blk_n_AR;
wire    ap_CS_fsm_state2;
reg    gmem1_blk_n_AR;
wire   [63:0] add_ln41_fu_160_p2;
reg   [63:0] add_ln41_reg_188;
wire   [63:0] add_ln41_1_fu_166_p2;
reg   [63:0] add_ln41_1_reg_194;
wire    grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_ap_start;
wire    grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_ap_done;
wire    grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_ap_idle;
wire    grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_ap_ready;
wire    grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_AWVALID;
wire   [63:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_AWADDR;
wire   [0:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_AWID;
wire   [31:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_AWLEN;
wire   [2:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_AWSIZE;
wire   [1:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_AWBURST;
wire   [1:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_AWLOCK;
wire   [3:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_AWCACHE;
wire   [2:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_AWPROT;
wire   [3:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_AWQOS;
wire   [3:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_AWREGION;
wire   [0:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_AWUSER;
wire    grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_WVALID;
wire   [7:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_WDATA;
wire   [0:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_WSTRB;
wire    grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_WLAST;
wire   [0:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_WID;
wire   [0:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_WUSER;
wire    grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_ARVALID;
wire   [63:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_ARADDR;
wire   [0:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_ARID;
wire   [31:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_ARLEN;
wire   [2:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_ARSIZE;
wire   [1:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_ARBURST;
wire   [1:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_ARLOCK;
wire   [3:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_ARCACHE;
wire   [2:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_ARPROT;
wire   [3:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_ARQOS;
wire   [3:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_ARREGION;
wire   [0:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_ARUSER;
wire    grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_RREADY;
wire    grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_BREADY;
wire    grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_AWVALID;
wire   [63:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_AWADDR;
wire   [0:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_AWID;
wire   [31:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_AWLEN;
wire   [2:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_AWSIZE;
wire   [1:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_AWBURST;
wire   [1:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_AWLOCK;
wire   [3:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_AWCACHE;
wire   [2:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_AWPROT;
wire   [3:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_AWQOS;
wire   [3:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_AWREGION;
wire   [0:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_AWUSER;
wire    grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_WVALID;
wire   [7:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_WDATA;
wire   [0:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_WSTRB;
wire    grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_WLAST;
wire   [0:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_WID;
wire   [0:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_WUSER;
wire    grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_ARVALID;
wire   [63:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_ARADDR;
wire   [0:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_ARID;
wire   [31:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_ARLEN;
wire   [2:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_ARSIZE;
wire   [1:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_ARBURST;
wire   [1:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_ARLOCK;
wire   [3:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_ARCACHE;
wire   [2:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_ARPROT;
wire   [3:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_ARQOS;
wire   [3:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_ARREGION;
wire   [0:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_ARUSER;
wire    grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_RREADY;
wire    grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_BREADY;
wire   [4:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_0_address0;
wire    grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_0_ce0;
wire    grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_0_we0;
wire   [7:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_0_d0;
wire   [4:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_0_address0;
wire    grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_0_ce0;
wire    grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_0_we0;
wire   [7:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_0_d0;
wire   [4:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_1_address0;
wire    grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_1_ce0;
wire    grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_1_we0;
wire   [7:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_1_d0;
wire   [4:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_1_address0;
wire    grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_1_ce0;
wire    grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_1_we0;
wire   [7:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_1_d0;
wire   [4:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_2_address0;
wire    grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_2_ce0;
wire    grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_2_we0;
wire   [7:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_2_d0;
wire   [4:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_2_address0;
wire    grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_2_ce0;
wire    grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_2_we0;
wire   [7:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_2_d0;
wire   [4:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_3_address0;
wire    grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_3_ce0;
wire    grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_3_we0;
wire   [7:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_3_d0;
wire   [4:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_3_address0;
wire    grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_3_ce0;
wire    grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_3_we0;
wire   [7:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_3_d0;
wire   [4:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_4_address0;
wire    grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_4_ce0;
wire    grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_4_we0;
wire   [7:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_4_d0;
wire   [4:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_4_address0;
wire    grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_4_ce0;
wire    grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_4_we0;
wire   [7:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_4_d0;
wire   [4:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_5_address0;
wire    grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_5_ce0;
wire    grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_5_we0;
wire   [7:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_5_d0;
wire   [4:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_5_address0;
wire    grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_5_ce0;
wire    grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_5_we0;
wire   [7:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_5_d0;
wire   [4:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_6_address0;
wire    grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_6_ce0;
wire    grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_6_we0;
wire   [7:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_6_d0;
wire   [4:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_6_address0;
wire    grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_6_ce0;
wire    grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_6_we0;
wire   [7:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_6_d0;
wire   [4:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_7_address0;
wire    grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_7_ce0;
wire    grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_7_we0;
wire   [7:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_7_d0;
wire   [4:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_7_address0;
wire    grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_7_ce0;
wire    grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_7_we0;
wire   [7:0] grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_7_d0;
reg    grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_ap_start_reg;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
reg    ap_block_state2_io;
reg    ap_block_state1;
wire   [15:0] shl_ln_i_fu_148_p3;
wire   [63:0] zext_ln41_fu_156_p1;
reg   [7:0] ap_return_preg;
reg   [9:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 10'd1;
#0 grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_ap_start_reg = 1'b0;
#0 ap_return_preg = 8'd0;
end

image_diff_posterize_Read_Loop_proc_Pipeline_Read_Loop grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_ap_start),
    .ap_done(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_ap_done),
    .ap_idle(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_ap_idle),
    .ap_ready(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_ap_ready),
    .m_axi_gmem0_AWVALID(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_AWVALID),
    .m_axi_gmem0_AWREADY(1'b0),
    .m_axi_gmem0_AWADDR(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_AWADDR),
    .m_axi_gmem0_AWID(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_AWID),
    .m_axi_gmem0_AWLEN(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_AWLEN),
    .m_axi_gmem0_AWSIZE(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_AWSIZE),
    .m_axi_gmem0_AWBURST(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_AWBURST),
    .m_axi_gmem0_AWLOCK(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_AWLOCK),
    .m_axi_gmem0_AWCACHE(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_AWCACHE),
    .m_axi_gmem0_AWPROT(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_AWPROT),
    .m_axi_gmem0_AWQOS(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_AWQOS),
    .m_axi_gmem0_AWREGION(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_AWREGION),
    .m_axi_gmem0_AWUSER(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_AWUSER),
    .m_axi_gmem0_WVALID(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_WVALID),
    .m_axi_gmem0_WREADY(1'b0),
    .m_axi_gmem0_WDATA(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_WDATA),
    .m_axi_gmem0_WSTRB(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_WSTRB),
    .m_axi_gmem0_WLAST(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_WLAST),
    .m_axi_gmem0_WID(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_WID),
    .m_axi_gmem0_WUSER(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_WUSER),
    .m_axi_gmem0_ARVALID(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_ARVALID),
    .m_axi_gmem0_ARREADY(m_axi_gmem0_ARREADY),
    .m_axi_gmem0_ARADDR(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_ARADDR),
    .m_axi_gmem0_ARID(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_ARID),
    .m_axi_gmem0_ARLEN(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_ARLEN),
    .m_axi_gmem0_ARSIZE(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_ARSIZE),
    .m_axi_gmem0_ARBURST(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_ARBURST),
    .m_axi_gmem0_ARLOCK(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_ARLOCK),
    .m_axi_gmem0_ARCACHE(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_ARCACHE),
    .m_axi_gmem0_ARPROT(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_ARPROT),
    .m_axi_gmem0_ARQOS(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_ARQOS),
    .m_axi_gmem0_ARREGION(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_ARREGION),
    .m_axi_gmem0_ARUSER(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_ARUSER),
    .m_axi_gmem0_RVALID(m_axi_gmem0_RVALID),
    .m_axi_gmem0_RREADY(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_RREADY),
    .m_axi_gmem0_RDATA(m_axi_gmem0_RDATA),
    .m_axi_gmem0_RLAST(m_axi_gmem0_RLAST),
    .m_axi_gmem0_RID(m_axi_gmem0_RID),
    .m_axi_gmem0_RFIFONUM(m_axi_gmem0_RFIFONUM),
    .m_axi_gmem0_RUSER(m_axi_gmem0_RUSER),
    .m_axi_gmem0_RRESP(m_axi_gmem0_RRESP),
    .m_axi_gmem0_BVALID(1'b0),
    .m_axi_gmem0_BREADY(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_BREADY),
    .m_axi_gmem0_BRESP(2'd0),
    .m_axi_gmem0_BID(1'd0),
    .m_axi_gmem0_BUSER(1'd0),
    .m_axi_gmem1_AWVALID(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_AWVALID),
    .m_axi_gmem1_AWREADY(1'b0),
    .m_axi_gmem1_AWADDR(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_AWADDR),
    .m_axi_gmem1_AWID(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_AWID),
    .m_axi_gmem1_AWLEN(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_AWLEN),
    .m_axi_gmem1_AWSIZE(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_AWSIZE),
    .m_axi_gmem1_AWBURST(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_AWBURST),
    .m_axi_gmem1_AWLOCK(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_AWLOCK),
    .m_axi_gmem1_AWCACHE(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_AWCACHE),
    .m_axi_gmem1_AWPROT(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_AWPROT),
    .m_axi_gmem1_AWQOS(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_AWQOS),
    .m_axi_gmem1_AWREGION(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_AWREGION),
    .m_axi_gmem1_AWUSER(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_AWUSER),
    .m_axi_gmem1_WVALID(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_WVALID),
    .m_axi_gmem1_WREADY(1'b0),
    .m_axi_gmem1_WDATA(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_WDATA),
    .m_axi_gmem1_WSTRB(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_WSTRB),
    .m_axi_gmem1_WLAST(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_WLAST),
    .m_axi_gmem1_WID(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_WID),
    .m_axi_gmem1_WUSER(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_WUSER),
    .m_axi_gmem1_ARVALID(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_ARVALID),
    .m_axi_gmem1_ARREADY(m_axi_gmem1_ARREADY),
    .m_axi_gmem1_ARADDR(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_ARADDR),
    .m_axi_gmem1_ARID(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_ARID),
    .m_axi_gmem1_ARLEN(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_ARLEN),
    .m_axi_gmem1_ARSIZE(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_ARSIZE),
    .m_axi_gmem1_ARBURST(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_ARBURST),
    .m_axi_gmem1_ARLOCK(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_ARLOCK),
    .m_axi_gmem1_ARCACHE(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_ARCACHE),
    .m_axi_gmem1_ARPROT(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_ARPROT),
    .m_axi_gmem1_ARQOS(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_ARQOS),
    .m_axi_gmem1_ARREGION(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_ARREGION),
    .m_axi_gmem1_ARUSER(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_ARUSER),
    .m_axi_gmem1_RVALID(m_axi_gmem1_RVALID),
    .m_axi_gmem1_RREADY(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_RREADY),
    .m_axi_gmem1_RDATA(m_axi_gmem1_RDATA),
    .m_axi_gmem1_RLAST(m_axi_gmem1_RLAST),
    .m_axi_gmem1_RID(m_axi_gmem1_RID),
    .m_axi_gmem1_RFIFONUM(m_axi_gmem1_RFIFONUM),
    .m_axi_gmem1_RUSER(m_axi_gmem1_RUSER),
    .m_axi_gmem1_RRESP(m_axi_gmem1_RRESP),
    .m_axi_gmem1_BVALID(1'b0),
    .m_axi_gmem1_BREADY(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_BREADY),
    .m_axi_gmem1_BRESP(2'd0),
    .m_axi_gmem1_BID(1'd0),
    .m_axi_gmem1_BUSER(1'd0),
    .add_ln41_1_i(add_ln41_1_reg_194),
    .add_ln41_i(add_ln41_reg_188),
    .image_diff_posterize_rowA_0_address0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_0_address0),
    .image_diff_posterize_rowA_0_ce0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_0_ce0),
    .image_diff_posterize_rowA_0_we0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_0_we0),
    .image_diff_posterize_rowA_0_d0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_0_d0),
    .image_diff_posterize_rowB_0_address0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_0_address0),
    .image_diff_posterize_rowB_0_ce0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_0_ce0),
    .image_diff_posterize_rowB_0_we0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_0_we0),
    .image_diff_posterize_rowB_0_d0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_0_d0),
    .image_diff_posterize_rowA_1_address0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_1_address0),
    .image_diff_posterize_rowA_1_ce0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_1_ce0),
    .image_diff_posterize_rowA_1_we0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_1_we0),
    .image_diff_posterize_rowA_1_d0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_1_d0),
    .image_diff_posterize_rowB_1_address0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_1_address0),
    .image_diff_posterize_rowB_1_ce0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_1_ce0),
    .image_diff_posterize_rowB_1_we0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_1_we0),
    .image_diff_posterize_rowB_1_d0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_1_d0),
    .image_diff_posterize_rowA_2_address0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_2_address0),
    .image_diff_posterize_rowA_2_ce0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_2_ce0),
    .image_diff_posterize_rowA_2_we0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_2_we0),
    .image_diff_posterize_rowA_2_d0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_2_d0),
    .image_diff_posterize_rowB_2_address0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_2_address0),
    .image_diff_posterize_rowB_2_ce0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_2_ce0),
    .image_diff_posterize_rowB_2_we0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_2_we0),
    .image_diff_posterize_rowB_2_d0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_2_d0),
    .image_diff_posterize_rowA_3_address0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_3_address0),
    .image_diff_posterize_rowA_3_ce0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_3_ce0),
    .image_diff_posterize_rowA_3_we0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_3_we0),
    .image_diff_posterize_rowA_3_d0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_3_d0),
    .image_diff_posterize_rowB_3_address0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_3_address0),
    .image_diff_posterize_rowB_3_ce0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_3_ce0),
    .image_diff_posterize_rowB_3_we0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_3_we0),
    .image_diff_posterize_rowB_3_d0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_3_d0),
    .image_diff_posterize_rowA_4_address0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_4_address0),
    .image_diff_posterize_rowA_4_ce0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_4_ce0),
    .image_diff_posterize_rowA_4_we0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_4_we0),
    .image_diff_posterize_rowA_4_d0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_4_d0),
    .image_diff_posterize_rowB_4_address0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_4_address0),
    .image_diff_posterize_rowB_4_ce0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_4_ce0),
    .image_diff_posterize_rowB_4_we0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_4_we0),
    .image_diff_posterize_rowB_4_d0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_4_d0),
    .image_diff_posterize_rowA_5_address0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_5_address0),
    .image_diff_posterize_rowA_5_ce0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_5_ce0),
    .image_diff_posterize_rowA_5_we0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_5_we0),
    .image_diff_posterize_rowA_5_d0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_5_d0),
    .image_diff_posterize_rowB_5_address0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_5_address0),
    .image_diff_posterize_rowB_5_ce0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_5_ce0),
    .image_diff_posterize_rowB_5_we0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_5_we0),
    .image_diff_posterize_rowB_5_d0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_5_d0),
    .image_diff_posterize_rowA_6_address0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_6_address0),
    .image_diff_posterize_rowA_6_ce0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_6_ce0),
    .image_diff_posterize_rowA_6_we0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_6_we0),
    .image_diff_posterize_rowA_6_d0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_6_d0),
    .image_diff_posterize_rowB_6_address0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_6_address0),
    .image_diff_posterize_rowB_6_ce0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_6_ce0),
    .image_diff_posterize_rowB_6_we0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_6_we0),
    .image_diff_posterize_rowB_6_d0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_6_d0),
    .image_diff_posterize_rowA_7_address0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_7_address0),
    .image_diff_posterize_rowA_7_ce0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_7_ce0),
    .image_diff_posterize_rowA_7_we0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_7_we0),
    .image_diff_posterize_rowA_7_d0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_7_d0),
    .image_diff_posterize_rowB_7_address0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_7_address0),
    .image_diff_posterize_rowB_7_ce0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_7_ce0),
    .image_diff_posterize_rowB_7_we0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_7_we0),
    .image_diff_posterize_rowB_7_d0(grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_7_d0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 8'd0;
    end else begin
        if (((grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
            ap_return_preg <= i;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_ap_start_reg <= 1'b1;
        end else if ((grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_ap_ready == 1'b1)) begin
            grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        add_ln41_1_reg_194 <= add_ln41_1_fu_166_p2;
        add_ln41_reg_188 <= add_ln41_fu_160_p2;
    end
end

always @ (*) begin
    if ((grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_io)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        ap_return = i;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        gmem0_blk_n_AR = m_axi_gmem0_ARREADY;
    end else begin
        gmem0_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        gmem1_blk_n_AR = m_axi_gmem1_ARREADY;
    end else begin
        gmem1_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem0_ARADDR = add_ln41_reg_188;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem0_ARADDR = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_ARADDR;
    end else begin
        m_axi_gmem0_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem0_ARBURST = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_ARBURST;
    end else begin
        m_axi_gmem0_ARBURST = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem0_ARCACHE = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_ARCACHE;
    end else begin
        m_axi_gmem0_ARCACHE = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem0_ARID = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_ARID;
    end else begin
        m_axi_gmem0_ARID = 1'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem0_ARLEN = 32'd256;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem0_ARLEN = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_ARLEN;
    end else begin
        m_axi_gmem0_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem0_ARLOCK = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_ARLOCK;
    end else begin
        m_axi_gmem0_ARLOCK = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem0_ARPROT = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_ARPROT;
    end else begin
        m_axi_gmem0_ARPROT = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem0_ARQOS = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_ARQOS;
    end else begin
        m_axi_gmem0_ARQOS = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem0_ARREGION = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_ARREGION;
    end else begin
        m_axi_gmem0_ARREGION = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem0_ARSIZE = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_ARSIZE;
    end else begin
        m_axi_gmem0_ARSIZE = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem0_ARUSER = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_ARUSER;
    end else begin
        m_axi_gmem0_ARUSER = 1'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem0_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem0_ARVALID = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_ARVALID;
    end else begin
        m_axi_gmem0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem0_RREADY = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem0_RREADY;
    end else begin
        m_axi_gmem0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem1_ARADDR = add_ln41_1_reg_194;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem1_ARADDR = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_ARADDR;
    end else begin
        m_axi_gmem1_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem1_ARBURST = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_ARBURST;
    end else begin
        m_axi_gmem1_ARBURST = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem1_ARCACHE = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_ARCACHE;
    end else begin
        m_axi_gmem1_ARCACHE = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem1_ARID = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_ARID;
    end else begin
        m_axi_gmem1_ARID = 1'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem1_ARLEN = 32'd256;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem1_ARLEN = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_ARLEN;
    end else begin
        m_axi_gmem1_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem1_ARLOCK = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_ARLOCK;
    end else begin
        m_axi_gmem1_ARLOCK = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem1_ARPROT = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_ARPROT;
    end else begin
        m_axi_gmem1_ARPROT = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem1_ARQOS = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_ARQOS;
    end else begin
        m_axi_gmem1_ARQOS = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem1_ARREGION = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_ARREGION;
    end else begin
        m_axi_gmem1_ARREGION = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem1_ARSIZE = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_ARSIZE;
    end else begin
        m_axi_gmem1_ARSIZE = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem1_ARUSER = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_ARUSER;
    end else begin
        m_axi_gmem1_ARUSER = 1'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem1_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem1_ARVALID = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_ARVALID;
    end else begin
        m_axi_gmem1_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem1_RREADY = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_m_axi_gmem1_RREADY;
    end else begin
        m_axi_gmem1_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln41_1_fu_166_p2 = (zext_ln41_fu_156_p1 + B);

assign add_ln41_fu_160_p2 = (zext_ln41_fu_156_p1 + A);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state2_io = ((m_axi_gmem0_ARREADY == 1'b0) | (m_axi_gmem1_ARREADY == 1'b0));
end

assign grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_ap_start = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_ap_start_reg;

assign image_diff_posterize_rowA_0_address0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_0_address0;

assign image_diff_posterize_rowA_0_ce0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_0_ce0;

assign image_diff_posterize_rowA_0_d0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_0_d0;

assign image_diff_posterize_rowA_0_we0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_0_we0;

assign image_diff_posterize_rowA_1_address0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_1_address0;

assign image_diff_posterize_rowA_1_ce0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_1_ce0;

assign image_diff_posterize_rowA_1_d0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_1_d0;

assign image_diff_posterize_rowA_1_we0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_1_we0;

assign image_diff_posterize_rowA_2_address0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_2_address0;

assign image_diff_posterize_rowA_2_ce0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_2_ce0;

assign image_diff_posterize_rowA_2_d0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_2_d0;

assign image_diff_posterize_rowA_2_we0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_2_we0;

assign image_diff_posterize_rowA_3_address0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_3_address0;

assign image_diff_posterize_rowA_3_ce0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_3_ce0;

assign image_diff_posterize_rowA_3_d0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_3_d0;

assign image_diff_posterize_rowA_3_we0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_3_we0;

assign image_diff_posterize_rowA_4_address0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_4_address0;

assign image_diff_posterize_rowA_4_ce0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_4_ce0;

assign image_diff_posterize_rowA_4_d0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_4_d0;

assign image_diff_posterize_rowA_4_we0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_4_we0;

assign image_diff_posterize_rowA_5_address0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_5_address0;

assign image_diff_posterize_rowA_5_ce0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_5_ce0;

assign image_diff_posterize_rowA_5_d0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_5_d0;

assign image_diff_posterize_rowA_5_we0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_5_we0;

assign image_diff_posterize_rowA_6_address0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_6_address0;

assign image_diff_posterize_rowA_6_ce0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_6_ce0;

assign image_diff_posterize_rowA_6_d0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_6_d0;

assign image_diff_posterize_rowA_6_we0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_6_we0;

assign image_diff_posterize_rowA_7_address0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_7_address0;

assign image_diff_posterize_rowA_7_ce0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_7_ce0;

assign image_diff_posterize_rowA_7_d0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_7_d0;

assign image_diff_posterize_rowA_7_we0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowA_7_we0;

assign image_diff_posterize_rowB_0_address0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_0_address0;

assign image_diff_posterize_rowB_0_ce0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_0_ce0;

assign image_diff_posterize_rowB_0_d0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_0_d0;

assign image_diff_posterize_rowB_0_we0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_0_we0;

assign image_diff_posterize_rowB_1_address0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_1_address0;

assign image_diff_posterize_rowB_1_ce0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_1_ce0;

assign image_diff_posterize_rowB_1_d0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_1_d0;

assign image_diff_posterize_rowB_1_we0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_1_we0;

assign image_diff_posterize_rowB_2_address0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_2_address0;

assign image_diff_posterize_rowB_2_ce0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_2_ce0;

assign image_diff_posterize_rowB_2_d0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_2_d0;

assign image_diff_posterize_rowB_2_we0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_2_we0;

assign image_diff_posterize_rowB_3_address0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_3_address0;

assign image_diff_posterize_rowB_3_ce0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_3_ce0;

assign image_diff_posterize_rowB_3_d0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_3_d0;

assign image_diff_posterize_rowB_3_we0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_3_we0;

assign image_diff_posterize_rowB_4_address0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_4_address0;

assign image_diff_posterize_rowB_4_ce0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_4_ce0;

assign image_diff_posterize_rowB_4_d0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_4_d0;

assign image_diff_posterize_rowB_4_we0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_4_we0;

assign image_diff_posterize_rowB_5_address0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_5_address0;

assign image_diff_posterize_rowB_5_ce0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_5_ce0;

assign image_diff_posterize_rowB_5_d0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_5_d0;

assign image_diff_posterize_rowB_5_we0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_5_we0;

assign image_diff_posterize_rowB_6_address0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_6_address0;

assign image_diff_posterize_rowB_6_ce0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_6_ce0;

assign image_diff_posterize_rowB_6_d0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_6_d0;

assign image_diff_posterize_rowB_6_we0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_6_we0;

assign image_diff_posterize_rowB_7_address0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_7_address0;

assign image_diff_posterize_rowB_7_ce0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_7_ce0;

assign image_diff_posterize_rowB_7_d0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_7_d0;

assign image_diff_posterize_rowB_7_we0 = grp_Read_Loop_proc_Pipeline_Read_Loop_fu_106_image_diff_posterize_rowB_7_we0;

assign m_axi_gmem0_AWADDR = 64'd0;

assign m_axi_gmem0_AWBURST = 2'd0;

assign m_axi_gmem0_AWCACHE = 4'd0;

assign m_axi_gmem0_AWID = 1'd0;

assign m_axi_gmem0_AWLEN = 32'd0;

assign m_axi_gmem0_AWLOCK = 2'd0;

assign m_axi_gmem0_AWPROT = 3'd0;

assign m_axi_gmem0_AWQOS = 4'd0;

assign m_axi_gmem0_AWREGION = 4'd0;

assign m_axi_gmem0_AWSIZE = 3'd0;

assign m_axi_gmem0_AWUSER = 1'd0;

assign m_axi_gmem0_AWVALID = 1'b0;

assign m_axi_gmem0_BREADY = 1'b0;

assign m_axi_gmem0_WDATA = 8'd0;

assign m_axi_gmem0_WID = 1'd0;

assign m_axi_gmem0_WLAST = 1'b0;

assign m_axi_gmem0_WSTRB = 1'd0;

assign m_axi_gmem0_WUSER = 1'd0;

assign m_axi_gmem0_WVALID = 1'b0;

assign m_axi_gmem1_AWADDR = 64'd0;

assign m_axi_gmem1_AWBURST = 2'd0;

assign m_axi_gmem1_AWCACHE = 4'd0;

assign m_axi_gmem1_AWID = 1'd0;

assign m_axi_gmem1_AWLEN = 32'd0;

assign m_axi_gmem1_AWLOCK = 2'd0;

assign m_axi_gmem1_AWPROT = 3'd0;

assign m_axi_gmem1_AWQOS = 4'd0;

assign m_axi_gmem1_AWREGION = 4'd0;

assign m_axi_gmem1_AWSIZE = 3'd0;

assign m_axi_gmem1_AWUSER = 1'd0;

assign m_axi_gmem1_AWVALID = 1'b0;

assign m_axi_gmem1_BREADY = 1'b0;

assign m_axi_gmem1_WDATA = 8'd0;

assign m_axi_gmem1_WID = 1'd0;

assign m_axi_gmem1_WLAST = 1'b0;

assign m_axi_gmem1_WSTRB = 1'd0;

assign m_axi_gmem1_WUSER = 1'd0;

assign m_axi_gmem1_WVALID = 1'b0;

assign shl_ln_i_fu_148_p3 = {{i}, {8'd0}};

assign zext_ln41_fu_156_p1 = shl_ln_i_fu_148_p3;

endmodule //image_diff_posterize_Read_Loop_proc
