-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity image_diff_posterize_Read_Loop_proc_Pipeline_Read_Loop is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem0_AWREADY : IN STD_LOGIC;
    m_axi_gmem0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_WVALID : OUT STD_LOGIC;
    m_axi_gmem0_WREADY : IN STD_LOGIC;
    m_axi_gmem0_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem0_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_WLAST : OUT STD_LOGIC;
    m_axi_gmem0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem0_ARREADY : IN STD_LOGIC;
    m_axi_gmem0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RVALID : IN STD_LOGIC;
    m_axi_gmem0_RREADY : OUT STD_LOGIC;
    m_axi_gmem0_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem0_RLAST : IN STD_LOGIC;
    m_axi_gmem0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RFIFONUM : IN STD_LOGIC_VECTOR (10 downto 0);
    m_axi_gmem0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_BVALID : IN STD_LOGIC;
    m_axi_gmem0_BREADY : OUT STD_LOGIC;
    m_axi_gmem0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_AWVALID : OUT STD_LOGIC;
    m_axi_gmem1_AWREADY : IN STD_LOGIC;
    m_axi_gmem1_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_WVALID : OUT STD_LOGIC;
    m_axi_gmem1_WREADY : IN STD_LOGIC;
    m_axi_gmem1_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem1_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_WLAST : OUT STD_LOGIC;
    m_axi_gmem1_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_ARVALID : OUT STD_LOGIC;
    m_axi_gmem1_ARREADY : IN STD_LOGIC;
    m_axi_gmem1_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_RVALID : IN STD_LOGIC;
    m_axi_gmem1_RREADY : OUT STD_LOGIC;
    m_axi_gmem1_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem1_RLAST : IN STD_LOGIC;
    m_axi_gmem1_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_RFIFONUM : IN STD_LOGIC_VECTOR (10 downto 0);
    m_axi_gmem1_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_BVALID : IN STD_LOGIC;
    m_axi_gmem1_BREADY : OUT STD_LOGIC;
    m_axi_gmem1_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    add_ln41_1_i : IN STD_LOGIC_VECTOR (63 downto 0);
    add_ln41_i : IN STD_LOGIC_VECTOR (63 downto 0);
    image_diff_posterize_rowA_0_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    image_diff_posterize_rowA_0_ce0 : OUT STD_LOGIC;
    image_diff_posterize_rowA_0_we0 : OUT STD_LOGIC;
    image_diff_posterize_rowA_0_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    image_diff_posterize_rowB_0_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    image_diff_posterize_rowB_0_ce0 : OUT STD_LOGIC;
    image_diff_posterize_rowB_0_we0 : OUT STD_LOGIC;
    image_diff_posterize_rowB_0_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    image_diff_posterize_rowA_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    image_diff_posterize_rowA_1_ce0 : OUT STD_LOGIC;
    image_diff_posterize_rowA_1_we0 : OUT STD_LOGIC;
    image_diff_posterize_rowA_1_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    image_diff_posterize_rowB_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    image_diff_posterize_rowB_1_ce0 : OUT STD_LOGIC;
    image_diff_posterize_rowB_1_we0 : OUT STD_LOGIC;
    image_diff_posterize_rowB_1_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    image_diff_posterize_rowA_2_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    image_diff_posterize_rowA_2_ce0 : OUT STD_LOGIC;
    image_diff_posterize_rowA_2_we0 : OUT STD_LOGIC;
    image_diff_posterize_rowA_2_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    image_diff_posterize_rowB_2_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    image_diff_posterize_rowB_2_ce0 : OUT STD_LOGIC;
    image_diff_posterize_rowB_2_we0 : OUT STD_LOGIC;
    image_diff_posterize_rowB_2_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    image_diff_posterize_rowA_3_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    image_diff_posterize_rowA_3_ce0 : OUT STD_LOGIC;
    image_diff_posterize_rowA_3_we0 : OUT STD_LOGIC;
    image_diff_posterize_rowA_3_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    image_diff_posterize_rowB_3_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    image_diff_posterize_rowB_3_ce0 : OUT STD_LOGIC;
    image_diff_posterize_rowB_3_we0 : OUT STD_LOGIC;
    image_diff_posterize_rowB_3_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    image_diff_posterize_rowA_4_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    image_diff_posterize_rowA_4_ce0 : OUT STD_LOGIC;
    image_diff_posterize_rowA_4_we0 : OUT STD_LOGIC;
    image_diff_posterize_rowA_4_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    image_diff_posterize_rowB_4_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    image_diff_posterize_rowB_4_ce0 : OUT STD_LOGIC;
    image_diff_posterize_rowB_4_we0 : OUT STD_LOGIC;
    image_diff_posterize_rowB_4_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    image_diff_posterize_rowA_5_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    image_diff_posterize_rowA_5_ce0 : OUT STD_LOGIC;
    image_diff_posterize_rowA_5_we0 : OUT STD_LOGIC;
    image_diff_posterize_rowA_5_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    image_diff_posterize_rowB_5_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    image_diff_posterize_rowB_5_ce0 : OUT STD_LOGIC;
    image_diff_posterize_rowB_5_we0 : OUT STD_LOGIC;
    image_diff_posterize_rowB_5_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    image_diff_posterize_rowA_6_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    image_diff_posterize_rowA_6_ce0 : OUT STD_LOGIC;
    image_diff_posterize_rowA_6_we0 : OUT STD_LOGIC;
    image_diff_posterize_rowA_6_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    image_diff_posterize_rowB_6_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    image_diff_posterize_rowB_6_ce0 : OUT STD_LOGIC;
    image_diff_posterize_rowB_6_we0 : OUT STD_LOGIC;
    image_diff_posterize_rowB_6_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    image_diff_posterize_rowA_7_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    image_diff_posterize_rowA_7_ce0 : OUT STD_LOGIC;
    image_diff_posterize_rowA_7_we0 : OUT STD_LOGIC;
    image_diff_posterize_rowA_7_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    image_diff_posterize_rowB_7_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    image_diff_posterize_rowB_7_ce0 : OUT STD_LOGIC;
    image_diff_posterize_rowB_7_we0 : OUT STD_LOGIC;
    image_diff_posterize_rowB_7_d0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of image_diff_posterize_Read_Loop_proc_Pipeline_Read_Loop is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv9_100 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln47_fu_356_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem1_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal gmem0_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal lshr_ln_i_reg_427 : STD_LOGIC_VECTOR (4 downto 0);
    signal lshr_ln_i_reg_427_pp0_iter1_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln50_fu_378_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln50_reg_432 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln50_reg_432_pp0_iter1_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal gmem0_addr_read_reg_436 : STD_LOGIC_VECTOR (7 downto 0);
    signal gmem1_addr_read_reg_448 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln50_fu_387_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal j_fu_102 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln47_fu_362_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_j_2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component image_diff_posterize_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component image_diff_posterize_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    j_fu_102_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln47_fu_356_p2 = ap_const_lv1_0))) then 
                    j_fu_102 <= add_ln47_fu_362_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_102 <= ap_const_lv9_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                gmem0_addr_read_reg_436 <= m_axi_gmem0_RDATA;
                gmem1_addr_read_reg_448 <= m_axi_gmem1_RDATA;
                lshr_ln_i_reg_427_pp0_iter1_reg <= lshr_ln_i_reg_427;
                trunc_ln50_reg_432_pp0_iter1_reg <= trunc_ln50_reg_432;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln47_fu_356_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                lshr_ln_i_reg_427 <= ap_sig_allocacmp_j_2(7 downto 3);
                trunc_ln50_reg_432 <= trunc_ln50_fu_378_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln47_fu_362_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_j_2) + unsigned(ap_const_lv9_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, m_axi_gmem0_RVALID, m_axi_gmem1_RVALID)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((m_axi_gmem0_RVALID = ap_const_logic_0) or (m_axi_gmem1_RVALID = ap_const_logic_0)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, m_axi_gmem0_RVALID, m_axi_gmem1_RVALID)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((m_axi_gmem0_RVALID = ap_const_logic_0) or (m_axi_gmem1_RVALID = ap_const_logic_0)));
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state2_pp0_stage0_iter1_assign_proc : process(m_axi_gmem0_RVALID, m_axi_gmem1_RVALID)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((m_axi_gmem0_RVALID = ap_const_logic_0) or (m_axi_gmem1_RVALID = ap_const_logic_0));
    end process;

        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln47_fu_356_p2)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln47_fu_356_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_j_2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, j_fu_102, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_j_2 <= ap_const_lv9_0;
        else 
            ap_sig_allocacmp_j_2 <= j_fu_102;
        end if; 
    end process;


    gmem0_blk_n_R_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, m_axi_gmem0_RVALID, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            gmem0_blk_n_R <= m_axi_gmem0_RVALID;
        else 
            gmem0_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;


    gmem1_blk_n_R_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, m_axi_gmem1_RVALID, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            gmem1_blk_n_R <= m_axi_gmem1_RVALID;
        else 
            gmem1_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln47_fu_356_p2 <= "1" when (ap_sig_allocacmp_j_2 = ap_const_lv9_100) else "0";
    image_diff_posterize_rowA_0_address0 <= zext_ln50_fu_387_p1(5 - 1 downto 0);

    image_diff_posterize_rowA_0_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            image_diff_posterize_rowA_0_ce0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowA_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowA_0_d0 <= gmem0_addr_read_reg_436;

    image_diff_posterize_rowA_0_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln50_reg_432_pp0_iter1_reg)
    begin
        if (((trunc_ln50_reg_432_pp0_iter1_reg = ap_const_lv3_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            image_diff_posterize_rowA_0_we0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowA_0_we0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowA_1_address0 <= zext_ln50_fu_387_p1(5 - 1 downto 0);

    image_diff_posterize_rowA_1_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            image_diff_posterize_rowA_1_ce0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowA_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowA_1_d0 <= gmem0_addr_read_reg_436;

    image_diff_posterize_rowA_1_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln50_reg_432_pp0_iter1_reg)
    begin
        if (((trunc_ln50_reg_432_pp0_iter1_reg = ap_const_lv3_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            image_diff_posterize_rowA_1_we0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowA_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowA_2_address0 <= zext_ln50_fu_387_p1(5 - 1 downto 0);

    image_diff_posterize_rowA_2_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            image_diff_posterize_rowA_2_ce0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowA_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowA_2_d0 <= gmem0_addr_read_reg_436;

    image_diff_posterize_rowA_2_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln50_reg_432_pp0_iter1_reg)
    begin
        if (((trunc_ln50_reg_432_pp0_iter1_reg = ap_const_lv3_2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            image_diff_posterize_rowA_2_we0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowA_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowA_3_address0 <= zext_ln50_fu_387_p1(5 - 1 downto 0);

    image_diff_posterize_rowA_3_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            image_diff_posterize_rowA_3_ce0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowA_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowA_3_d0 <= gmem0_addr_read_reg_436;

    image_diff_posterize_rowA_3_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln50_reg_432_pp0_iter1_reg)
    begin
        if (((trunc_ln50_reg_432_pp0_iter1_reg = ap_const_lv3_3) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            image_diff_posterize_rowA_3_we0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowA_3_we0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowA_4_address0 <= zext_ln50_fu_387_p1(5 - 1 downto 0);

    image_diff_posterize_rowA_4_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            image_diff_posterize_rowA_4_ce0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowA_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowA_4_d0 <= gmem0_addr_read_reg_436;

    image_diff_posterize_rowA_4_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln50_reg_432_pp0_iter1_reg)
    begin
        if (((trunc_ln50_reg_432_pp0_iter1_reg = ap_const_lv3_4) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            image_diff_posterize_rowA_4_we0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowA_4_we0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowA_5_address0 <= zext_ln50_fu_387_p1(5 - 1 downto 0);

    image_diff_posterize_rowA_5_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            image_diff_posterize_rowA_5_ce0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowA_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowA_5_d0 <= gmem0_addr_read_reg_436;

    image_diff_posterize_rowA_5_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln50_reg_432_pp0_iter1_reg)
    begin
        if (((trunc_ln50_reg_432_pp0_iter1_reg = ap_const_lv3_5) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            image_diff_posterize_rowA_5_we0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowA_5_we0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowA_6_address0 <= zext_ln50_fu_387_p1(5 - 1 downto 0);

    image_diff_posterize_rowA_6_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            image_diff_posterize_rowA_6_ce0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowA_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowA_6_d0 <= gmem0_addr_read_reg_436;

    image_diff_posterize_rowA_6_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln50_reg_432_pp0_iter1_reg)
    begin
        if (((trunc_ln50_reg_432_pp0_iter1_reg = ap_const_lv3_6) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            image_diff_posterize_rowA_6_we0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowA_6_we0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowA_7_address0 <= zext_ln50_fu_387_p1(5 - 1 downto 0);

    image_diff_posterize_rowA_7_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            image_diff_posterize_rowA_7_ce0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowA_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowA_7_d0 <= gmem0_addr_read_reg_436;

    image_diff_posterize_rowA_7_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln50_reg_432_pp0_iter1_reg)
    begin
        if (((trunc_ln50_reg_432_pp0_iter1_reg = ap_const_lv3_7) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            image_diff_posterize_rowA_7_we0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowA_7_we0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowB_0_address0 <= zext_ln50_fu_387_p1(5 - 1 downto 0);

    image_diff_posterize_rowB_0_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            image_diff_posterize_rowB_0_ce0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowB_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowB_0_d0 <= gmem1_addr_read_reg_448;

    image_diff_posterize_rowB_0_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln50_reg_432_pp0_iter1_reg)
    begin
        if (((trunc_ln50_reg_432_pp0_iter1_reg = ap_const_lv3_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            image_diff_posterize_rowB_0_we0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowB_0_we0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowB_1_address0 <= zext_ln50_fu_387_p1(5 - 1 downto 0);

    image_diff_posterize_rowB_1_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            image_diff_posterize_rowB_1_ce0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowB_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowB_1_d0 <= gmem1_addr_read_reg_448;

    image_diff_posterize_rowB_1_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln50_reg_432_pp0_iter1_reg)
    begin
        if (((trunc_ln50_reg_432_pp0_iter1_reg = ap_const_lv3_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            image_diff_posterize_rowB_1_we0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowB_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowB_2_address0 <= zext_ln50_fu_387_p1(5 - 1 downto 0);

    image_diff_posterize_rowB_2_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            image_diff_posterize_rowB_2_ce0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowB_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowB_2_d0 <= gmem1_addr_read_reg_448;

    image_diff_posterize_rowB_2_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln50_reg_432_pp0_iter1_reg)
    begin
        if (((trunc_ln50_reg_432_pp0_iter1_reg = ap_const_lv3_2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            image_diff_posterize_rowB_2_we0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowB_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowB_3_address0 <= zext_ln50_fu_387_p1(5 - 1 downto 0);

    image_diff_posterize_rowB_3_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            image_diff_posterize_rowB_3_ce0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowB_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowB_3_d0 <= gmem1_addr_read_reg_448;

    image_diff_posterize_rowB_3_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln50_reg_432_pp0_iter1_reg)
    begin
        if (((trunc_ln50_reg_432_pp0_iter1_reg = ap_const_lv3_3) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            image_diff_posterize_rowB_3_we0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowB_3_we0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowB_4_address0 <= zext_ln50_fu_387_p1(5 - 1 downto 0);

    image_diff_posterize_rowB_4_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            image_diff_posterize_rowB_4_ce0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowB_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowB_4_d0 <= gmem1_addr_read_reg_448;

    image_diff_posterize_rowB_4_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln50_reg_432_pp0_iter1_reg)
    begin
        if (((trunc_ln50_reg_432_pp0_iter1_reg = ap_const_lv3_4) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            image_diff_posterize_rowB_4_we0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowB_4_we0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowB_5_address0 <= zext_ln50_fu_387_p1(5 - 1 downto 0);

    image_diff_posterize_rowB_5_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            image_diff_posterize_rowB_5_ce0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowB_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowB_5_d0 <= gmem1_addr_read_reg_448;

    image_diff_posterize_rowB_5_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln50_reg_432_pp0_iter1_reg)
    begin
        if (((trunc_ln50_reg_432_pp0_iter1_reg = ap_const_lv3_5) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            image_diff_posterize_rowB_5_we0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowB_5_we0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowB_6_address0 <= zext_ln50_fu_387_p1(5 - 1 downto 0);

    image_diff_posterize_rowB_6_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            image_diff_posterize_rowB_6_ce0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowB_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowB_6_d0 <= gmem1_addr_read_reg_448;

    image_diff_posterize_rowB_6_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln50_reg_432_pp0_iter1_reg)
    begin
        if (((trunc_ln50_reg_432_pp0_iter1_reg = ap_const_lv3_6) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            image_diff_posterize_rowB_6_we0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowB_6_we0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowB_7_address0 <= zext_ln50_fu_387_p1(5 - 1 downto 0);

    image_diff_posterize_rowB_7_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            image_diff_posterize_rowB_7_ce0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowB_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowB_7_d0 <= gmem1_addr_read_reg_448;

    image_diff_posterize_rowB_7_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln50_reg_432_pp0_iter1_reg)
    begin
        if (((trunc_ln50_reg_432_pp0_iter1_reg = ap_const_lv3_7) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            image_diff_posterize_rowB_7_we0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowB_7_we0 <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem0_ARADDR <= ap_const_lv64_0;
    m_axi_gmem0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem0_ARID <= ap_const_lv1_0;
    m_axi_gmem0_ARLEN <= ap_const_lv32_0;
    m_axi_gmem0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem0_ARUSER <= ap_const_lv1_0;
    m_axi_gmem0_ARVALID <= ap_const_logic_0;
    m_axi_gmem0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem0_AWID <= ap_const_lv1_0;
    m_axi_gmem0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem0_AWVALID <= ap_const_logic_0;
    m_axi_gmem0_BREADY <= ap_const_logic_0;

    m_axi_gmem0_RREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            m_axi_gmem0_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem0_WDATA <= ap_const_lv8_0;
    m_axi_gmem0_WID <= ap_const_lv1_0;
    m_axi_gmem0_WLAST <= ap_const_logic_0;
    m_axi_gmem0_WSTRB <= ap_const_lv1_0;
    m_axi_gmem0_WUSER <= ap_const_lv1_0;
    m_axi_gmem0_WVALID <= ap_const_logic_0;
    m_axi_gmem1_ARADDR <= ap_const_lv64_0;
    m_axi_gmem1_ARBURST <= ap_const_lv2_0;
    m_axi_gmem1_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem1_ARID <= ap_const_lv1_0;
    m_axi_gmem1_ARLEN <= ap_const_lv32_0;
    m_axi_gmem1_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem1_ARPROT <= ap_const_lv3_0;
    m_axi_gmem1_ARQOS <= ap_const_lv4_0;
    m_axi_gmem1_ARREGION <= ap_const_lv4_0;
    m_axi_gmem1_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem1_ARUSER <= ap_const_lv1_0;
    m_axi_gmem1_ARVALID <= ap_const_logic_0;
    m_axi_gmem1_AWADDR <= ap_const_lv64_0;
    m_axi_gmem1_AWBURST <= ap_const_lv2_0;
    m_axi_gmem1_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem1_AWID <= ap_const_lv1_0;
    m_axi_gmem1_AWLEN <= ap_const_lv32_0;
    m_axi_gmem1_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem1_AWPROT <= ap_const_lv3_0;
    m_axi_gmem1_AWQOS <= ap_const_lv4_0;
    m_axi_gmem1_AWREGION <= ap_const_lv4_0;
    m_axi_gmem1_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem1_AWUSER <= ap_const_lv1_0;
    m_axi_gmem1_AWVALID <= ap_const_logic_0;
    m_axi_gmem1_BREADY <= ap_const_logic_0;

    m_axi_gmem1_RREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            m_axi_gmem1_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem1_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem1_WDATA <= ap_const_lv8_0;
    m_axi_gmem1_WID <= ap_const_lv1_0;
    m_axi_gmem1_WLAST <= ap_const_logic_0;
    m_axi_gmem1_WSTRB <= ap_const_lv1_0;
    m_axi_gmem1_WUSER <= ap_const_lv1_0;
    m_axi_gmem1_WVALID <= ap_const_logic_0;
    trunc_ln50_fu_378_p1 <= ap_sig_allocacmp_j_2(3 - 1 downto 0);
    zext_ln50_fu_387_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln_i_reg_427_pp0_iter1_reg),64));
end behav;
