-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity image_diff_posterize_Col_Loop_proc is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    image_diff_posterize_rowA_0_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    image_diff_posterize_rowA_0_ce0 : OUT STD_LOGIC;
    image_diff_posterize_rowA_0_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    image_diff_posterize_rowA_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    image_diff_posterize_rowA_1_ce0 : OUT STD_LOGIC;
    image_diff_posterize_rowA_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    image_diff_posterize_rowA_2_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    image_diff_posterize_rowA_2_ce0 : OUT STD_LOGIC;
    image_diff_posterize_rowA_2_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    image_diff_posterize_rowA_3_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    image_diff_posterize_rowA_3_ce0 : OUT STD_LOGIC;
    image_diff_posterize_rowA_3_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    image_diff_posterize_rowA_4_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    image_diff_posterize_rowA_4_ce0 : OUT STD_LOGIC;
    image_diff_posterize_rowA_4_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    image_diff_posterize_rowA_5_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    image_diff_posterize_rowA_5_ce0 : OUT STD_LOGIC;
    image_diff_posterize_rowA_5_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    image_diff_posterize_rowA_6_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    image_diff_posterize_rowA_6_ce0 : OUT STD_LOGIC;
    image_diff_posterize_rowA_6_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    image_diff_posterize_rowA_7_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    image_diff_posterize_rowA_7_ce0 : OUT STD_LOGIC;
    image_diff_posterize_rowA_7_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    image_diff_posterize_rowB_0_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    image_diff_posterize_rowB_0_ce0 : OUT STD_LOGIC;
    image_diff_posterize_rowB_0_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    image_diff_posterize_rowB_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    image_diff_posterize_rowB_1_ce0 : OUT STD_LOGIC;
    image_diff_posterize_rowB_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    image_diff_posterize_rowB_2_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    image_diff_posterize_rowB_2_ce0 : OUT STD_LOGIC;
    image_diff_posterize_rowB_2_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    image_diff_posterize_rowB_3_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    image_diff_posterize_rowB_3_ce0 : OUT STD_LOGIC;
    image_diff_posterize_rowB_3_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    image_diff_posterize_rowB_4_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    image_diff_posterize_rowB_4_ce0 : OUT STD_LOGIC;
    image_diff_posterize_rowB_4_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    image_diff_posterize_rowB_5_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    image_diff_posterize_rowB_5_ce0 : OUT STD_LOGIC;
    image_diff_posterize_rowB_5_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    image_diff_posterize_rowB_6_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    image_diff_posterize_rowB_6_ce0 : OUT STD_LOGIC;
    image_diff_posterize_rowB_6_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    image_diff_posterize_rowB_7_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    image_diff_posterize_rowB_7_ce0 : OUT STD_LOGIC;
    image_diff_posterize_rowB_7_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    image_diff_posterize_rowC_0_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    image_diff_posterize_rowC_0_ce0 : OUT STD_LOGIC;
    image_diff_posterize_rowC_0_we0 : OUT STD_LOGIC;
    image_diff_posterize_rowC_0_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    image_diff_posterize_rowC_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    image_diff_posterize_rowC_1_ce0 : OUT STD_LOGIC;
    image_diff_posterize_rowC_1_we0 : OUT STD_LOGIC;
    image_diff_posterize_rowC_1_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    image_diff_posterize_rowC_2_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    image_diff_posterize_rowC_2_ce0 : OUT STD_LOGIC;
    image_diff_posterize_rowC_2_we0 : OUT STD_LOGIC;
    image_diff_posterize_rowC_2_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    image_diff_posterize_rowC_3_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    image_diff_posterize_rowC_3_ce0 : OUT STD_LOGIC;
    image_diff_posterize_rowC_3_we0 : OUT STD_LOGIC;
    image_diff_posterize_rowC_3_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    image_diff_posterize_rowC_4_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    image_diff_posterize_rowC_4_ce0 : OUT STD_LOGIC;
    image_diff_posterize_rowC_4_we0 : OUT STD_LOGIC;
    image_diff_posterize_rowC_4_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    image_diff_posterize_rowC_5_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    image_diff_posterize_rowC_5_ce0 : OUT STD_LOGIC;
    image_diff_posterize_rowC_5_we0 : OUT STD_LOGIC;
    image_diff_posterize_rowC_5_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    image_diff_posterize_rowC_6_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    image_diff_posterize_rowC_6_ce0 : OUT STD_LOGIC;
    image_diff_posterize_rowC_6_we0 : OUT STD_LOGIC;
    image_diff_posterize_rowC_6_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    image_diff_posterize_rowC_7_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    image_diff_posterize_rowC_7_ce0 : OUT STD_LOGIC;
    image_diff_posterize_rowC_7_we0 : OUT STD_LOGIC;
    image_diff_posterize_rowC_7_d0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of image_diff_posterize_Col_Loop_proc is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv9_8 : STD_LOGIC_VECTOR (8 downto 0) := "000001000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv8_60 : STD_LOGIC_VECTOR (7 downto 0) := "01100000";
    constant ap_const_lv8_80 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal tmp_fu_418_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal zext_ln81_fu_436_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln81_reg_1109 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal j_fu_94 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln76_fu_456_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_j_3 : STD_LOGIC_VECTOR (8 downto 0);
    signal lshr_ln_fu_426_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln81_1_fu_467_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln81_2_fu_471_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal diff_temp_fu_475_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln84_fu_481_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_1_fu_485_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln84_fu_493_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal diff_fu_499_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_fu_507_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln86_fu_517_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln87_fu_523_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln86_fu_529_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln81_3_fu_546_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln81_4_fu_550_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal diff_temp_1_fu_554_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln84_1_fu_560_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_3_fu_564_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln84_1_fu_572_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal diff_1_fu_578_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_4_fu_586_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln86_1_fu_596_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln87_1_fu_602_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln86_2_fu_608_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln81_5_fu_625_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln81_6_fu_629_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal diff_temp_2_fu_633_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln84_2_fu_639_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_5_fu_643_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln84_2_fu_651_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal diff_2_fu_657_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_6_fu_665_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln86_2_fu_675_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln87_2_fu_681_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln86_4_fu_687_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln81_7_fu_704_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln81_8_fu_708_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal diff_temp_3_fu_712_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln84_3_fu_718_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_7_fu_722_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln84_3_fu_730_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal diff_3_fu_736_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_8_fu_744_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln86_3_fu_754_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln87_3_fu_760_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln86_6_fu_766_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln81_9_fu_783_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln81_10_fu_787_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal diff_temp_4_fu_791_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln84_4_fu_797_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_9_fu_801_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln84_4_fu_809_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal diff_4_fu_815_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_10_fu_823_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln86_4_fu_833_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln87_4_fu_839_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln86_8_fu_845_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln81_11_fu_862_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln81_12_fu_866_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal diff_temp_5_fu_870_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln84_5_fu_876_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_11_fu_880_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln84_5_fu_888_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal diff_5_fu_894_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_12_fu_902_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln86_5_fu_912_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln87_5_fu_918_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln86_10_fu_924_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln81_13_fu_941_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln81_14_fu_945_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal diff_temp_6_fu_949_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln84_6_fu_955_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_13_fu_959_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln84_6_fu_967_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal diff_6_fu_973_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_14_fu_981_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln86_6_fu_991_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln87_6_fu_997_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln86_12_fu_1003_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln81_15_fu_1020_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln81_16_fu_1024_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal diff_temp_7_fu_1028_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln84_7_fu_1034_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_15_fu_1038_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln84_7_fu_1046_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal diff_7_fu_1052_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_16_fu_1060_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln86_7_fu_1070_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln87_7_fu_1076_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln86_14_fu_1082_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_268 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component image_diff_posterize_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_U : component image_diff_posterize_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_continue);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    j_fu_94_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_268)) then
                if ((tmp_fu_418_p3 = ap_const_lv1_0)) then 
                    j_fu_94 <= add_ln76_fu_456_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_94 <= ap_const_lv9_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_fu_418_p3 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                    zext_ln81_reg_1109(4 downto 0) <= zext_ln81_fu_436_p1(4 downto 0);
            end if;
        end if;
    end process;
    zext_ln81_reg_1109(63 downto 5) <= "00000000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln76_fu_456_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_j_3) + unsigned(ap_const_lv9_8));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_done_reg, ap_start_int)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_done_reg = ap_const_logic_1) and (ap_start_int = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_done_reg, ap_start_int)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_done_reg = ap_const_logic_1) and (ap_start_int = ap_const_logic_1)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_done_reg)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_done_reg = ap_const_logic_1);
    end process;

        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_268_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
                ap_condition_268 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, tmp_fu_418_p3, ap_start_int)
    begin
        if (((tmp_fu_418_p3 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_done_reg, ap_block_pp0_stage0_subdone, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_j_3_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, j_fu_94, ap_loop_init, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_j_3 <= ap_const_lv9_0;
        else 
            ap_sig_allocacmp_j_3 <= j_fu_94;
        end if; 
    end process;

    diff_1_fu_578_p3 <= 
        sub_ln84_1_fu_572_p2 when (tmp_3_fu_564_p3(0) = '1') else 
        trunc_ln84_1_fu_560_p1;
    diff_2_fu_657_p3 <= 
        sub_ln84_2_fu_651_p2 when (tmp_5_fu_643_p3(0) = '1') else 
        trunc_ln84_2_fu_639_p1;
    diff_3_fu_736_p3 <= 
        sub_ln84_3_fu_730_p2 when (tmp_7_fu_722_p3(0) = '1') else 
        trunc_ln84_3_fu_718_p1;
    diff_4_fu_815_p3 <= 
        sub_ln84_4_fu_809_p2 when (tmp_9_fu_801_p3(0) = '1') else 
        trunc_ln84_4_fu_797_p1;
    diff_5_fu_894_p3 <= 
        sub_ln84_5_fu_888_p2 when (tmp_11_fu_880_p3(0) = '1') else 
        trunc_ln84_5_fu_876_p1;
    diff_6_fu_973_p3 <= 
        sub_ln84_6_fu_967_p2 when (tmp_13_fu_959_p3(0) = '1') else 
        trunc_ln84_6_fu_955_p1;
    diff_7_fu_1052_p3 <= 
        sub_ln84_7_fu_1046_p2 when (tmp_15_fu_1038_p3(0) = '1') else 
        trunc_ln84_7_fu_1034_p1;
    diff_fu_499_p3 <= 
        sub_ln84_fu_493_p2 when (tmp_1_fu_485_p3(0) = '1') else 
        trunc_ln84_fu_481_p1;
    diff_temp_1_fu_554_p2 <= std_logic_vector(unsigned(zext_ln81_3_fu_546_p1) - unsigned(zext_ln81_4_fu_550_p1));
    diff_temp_2_fu_633_p2 <= std_logic_vector(unsigned(zext_ln81_5_fu_625_p1) - unsigned(zext_ln81_6_fu_629_p1));
    diff_temp_3_fu_712_p2 <= std_logic_vector(unsigned(zext_ln81_7_fu_704_p1) - unsigned(zext_ln81_8_fu_708_p1));
    diff_temp_4_fu_791_p2 <= std_logic_vector(unsigned(zext_ln81_9_fu_783_p1) - unsigned(zext_ln81_10_fu_787_p1));
    diff_temp_5_fu_870_p2 <= std_logic_vector(unsigned(zext_ln81_11_fu_862_p1) - unsigned(zext_ln81_12_fu_866_p1));
    diff_temp_6_fu_949_p2 <= std_logic_vector(unsigned(zext_ln81_13_fu_941_p1) - unsigned(zext_ln81_14_fu_945_p1));
    diff_temp_7_fu_1028_p2 <= std_logic_vector(unsigned(zext_ln81_15_fu_1020_p1) - unsigned(zext_ln81_16_fu_1024_p1));
    diff_temp_fu_475_p2 <= std_logic_vector(unsigned(zext_ln81_1_fu_467_p1) - unsigned(zext_ln81_2_fu_471_p1));
    icmp_ln86_1_fu_596_p2 <= "1" when (tmp_4_fu_586_p4 = ap_const_lv3_0) else "0";
    icmp_ln86_2_fu_675_p2 <= "1" when (tmp_6_fu_665_p4 = ap_const_lv3_0) else "0";
    icmp_ln86_3_fu_754_p2 <= "1" when (tmp_8_fu_744_p4 = ap_const_lv3_0) else "0";
    icmp_ln86_4_fu_833_p2 <= "1" when (tmp_10_fu_823_p4 = ap_const_lv3_0) else "0";
    icmp_ln86_5_fu_912_p2 <= "1" when (tmp_12_fu_902_p4 = ap_const_lv3_0) else "0";
    icmp_ln86_6_fu_991_p2 <= "1" when (tmp_14_fu_981_p4 = ap_const_lv3_0) else "0";
    icmp_ln86_7_fu_1070_p2 <= "1" when (tmp_16_fu_1060_p4 = ap_const_lv3_0) else "0";
    icmp_ln86_fu_517_p2 <= "1" when (tmp_2_fu_507_p4 = ap_const_lv3_0) else "0";
    icmp_ln87_1_fu_602_p2 <= "1" when (unsigned(diff_1_fu_578_p3) < unsigned(ap_const_lv8_60)) else "0";
    icmp_ln87_2_fu_681_p2 <= "1" when (unsigned(diff_2_fu_657_p3) < unsigned(ap_const_lv8_60)) else "0";
    icmp_ln87_3_fu_760_p2 <= "1" when (unsigned(diff_3_fu_736_p3) < unsigned(ap_const_lv8_60)) else "0";
    icmp_ln87_4_fu_839_p2 <= "1" when (unsigned(diff_4_fu_815_p3) < unsigned(ap_const_lv8_60)) else "0";
    icmp_ln87_5_fu_918_p2 <= "1" when (unsigned(diff_5_fu_894_p3) < unsigned(ap_const_lv8_60)) else "0";
    icmp_ln87_6_fu_997_p2 <= "1" when (unsigned(diff_6_fu_973_p3) < unsigned(ap_const_lv8_60)) else "0";
    icmp_ln87_7_fu_1076_p2 <= "1" when (unsigned(diff_7_fu_1052_p3) < unsigned(ap_const_lv8_60)) else "0";
    icmp_ln87_fu_523_p2 <= "1" when (unsigned(diff_fu_499_p3) < unsigned(ap_const_lv8_60)) else "0";
    image_diff_posterize_rowA_0_address0 <= zext_ln81_fu_436_p1(5 - 1 downto 0);

    image_diff_posterize_rowA_0_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            image_diff_posterize_rowA_0_ce0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowA_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowA_1_address0 <= zext_ln81_fu_436_p1(5 - 1 downto 0);

    image_diff_posterize_rowA_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            image_diff_posterize_rowA_1_ce0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowA_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowA_2_address0 <= zext_ln81_fu_436_p1(5 - 1 downto 0);

    image_diff_posterize_rowA_2_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            image_diff_posterize_rowA_2_ce0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowA_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowA_3_address0 <= zext_ln81_fu_436_p1(5 - 1 downto 0);

    image_diff_posterize_rowA_3_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            image_diff_posterize_rowA_3_ce0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowA_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowA_4_address0 <= zext_ln81_fu_436_p1(5 - 1 downto 0);

    image_diff_posterize_rowA_4_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            image_diff_posterize_rowA_4_ce0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowA_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowA_5_address0 <= zext_ln81_fu_436_p1(5 - 1 downto 0);

    image_diff_posterize_rowA_5_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            image_diff_posterize_rowA_5_ce0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowA_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowA_6_address0 <= zext_ln81_fu_436_p1(5 - 1 downto 0);

    image_diff_posterize_rowA_6_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            image_diff_posterize_rowA_6_ce0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowA_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowA_7_address0 <= zext_ln81_fu_436_p1(5 - 1 downto 0);

    image_diff_posterize_rowA_7_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            image_diff_posterize_rowA_7_ce0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowA_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowB_0_address0 <= zext_ln81_fu_436_p1(5 - 1 downto 0);

    image_diff_posterize_rowB_0_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            image_diff_posterize_rowB_0_ce0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowB_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowB_1_address0 <= zext_ln81_fu_436_p1(5 - 1 downto 0);

    image_diff_posterize_rowB_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            image_diff_posterize_rowB_1_ce0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowB_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowB_2_address0 <= zext_ln81_fu_436_p1(5 - 1 downto 0);

    image_diff_posterize_rowB_2_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            image_diff_posterize_rowB_2_ce0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowB_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowB_3_address0 <= zext_ln81_fu_436_p1(5 - 1 downto 0);

    image_diff_posterize_rowB_3_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            image_diff_posterize_rowB_3_ce0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowB_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowB_4_address0 <= zext_ln81_fu_436_p1(5 - 1 downto 0);

    image_diff_posterize_rowB_4_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            image_diff_posterize_rowB_4_ce0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowB_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowB_5_address0 <= zext_ln81_fu_436_p1(5 - 1 downto 0);

    image_diff_posterize_rowB_5_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            image_diff_posterize_rowB_5_ce0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowB_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowB_6_address0 <= zext_ln81_fu_436_p1(5 - 1 downto 0);

    image_diff_posterize_rowB_6_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            image_diff_posterize_rowB_6_ce0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowB_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowB_7_address0 <= zext_ln81_fu_436_p1(5 - 1 downto 0);

    image_diff_posterize_rowB_7_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            image_diff_posterize_rowB_7_ce0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowB_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowC_0_address0 <= zext_ln81_reg_1109(5 - 1 downto 0);

    image_diff_posterize_rowC_0_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            image_diff_posterize_rowC_0_ce0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowC_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowC_0_d0 <= 
        select_ln86_fu_529_p3 when (icmp_ln87_fu_523_p2(0) = '1') else 
        ap_const_lv8_FF;

    image_diff_posterize_rowC_0_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            image_diff_posterize_rowC_0_we0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowC_0_we0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowC_1_address0 <= zext_ln81_reg_1109(5 - 1 downto 0);

    image_diff_posterize_rowC_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            image_diff_posterize_rowC_1_ce0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowC_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowC_1_d0 <= 
        select_ln86_2_fu_608_p3 when (icmp_ln87_1_fu_602_p2(0) = '1') else 
        ap_const_lv8_FF;

    image_diff_posterize_rowC_1_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            image_diff_posterize_rowC_1_we0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowC_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowC_2_address0 <= zext_ln81_reg_1109(5 - 1 downto 0);

    image_diff_posterize_rowC_2_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            image_diff_posterize_rowC_2_ce0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowC_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowC_2_d0 <= 
        select_ln86_4_fu_687_p3 when (icmp_ln87_2_fu_681_p2(0) = '1') else 
        ap_const_lv8_FF;

    image_diff_posterize_rowC_2_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            image_diff_posterize_rowC_2_we0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowC_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowC_3_address0 <= zext_ln81_reg_1109(5 - 1 downto 0);

    image_diff_posterize_rowC_3_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            image_diff_posterize_rowC_3_ce0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowC_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowC_3_d0 <= 
        select_ln86_6_fu_766_p3 when (icmp_ln87_3_fu_760_p2(0) = '1') else 
        ap_const_lv8_FF;

    image_diff_posterize_rowC_3_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            image_diff_posterize_rowC_3_we0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowC_3_we0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowC_4_address0 <= zext_ln81_reg_1109(5 - 1 downto 0);

    image_diff_posterize_rowC_4_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            image_diff_posterize_rowC_4_ce0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowC_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowC_4_d0 <= 
        select_ln86_8_fu_845_p3 when (icmp_ln87_4_fu_839_p2(0) = '1') else 
        ap_const_lv8_FF;

    image_diff_posterize_rowC_4_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            image_diff_posterize_rowC_4_we0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowC_4_we0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowC_5_address0 <= zext_ln81_reg_1109(5 - 1 downto 0);

    image_diff_posterize_rowC_5_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            image_diff_posterize_rowC_5_ce0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowC_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowC_5_d0 <= 
        select_ln86_10_fu_924_p3 when (icmp_ln87_5_fu_918_p2(0) = '1') else 
        ap_const_lv8_FF;

    image_diff_posterize_rowC_5_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            image_diff_posterize_rowC_5_we0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowC_5_we0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowC_6_address0 <= zext_ln81_reg_1109(5 - 1 downto 0);

    image_diff_posterize_rowC_6_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            image_diff_posterize_rowC_6_ce0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowC_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowC_6_d0 <= 
        select_ln86_12_fu_1003_p3 when (icmp_ln87_6_fu_997_p2(0) = '1') else 
        ap_const_lv8_FF;

    image_diff_posterize_rowC_6_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            image_diff_posterize_rowC_6_we0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowC_6_we0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowC_7_address0 <= zext_ln81_reg_1109(5 - 1 downto 0);

    image_diff_posterize_rowC_7_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            image_diff_posterize_rowC_7_ce0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowC_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    image_diff_posterize_rowC_7_d0 <= 
        select_ln86_14_fu_1082_p3 when (icmp_ln87_7_fu_1076_p2(0) = '1') else 
        ap_const_lv8_FF;

    image_diff_posterize_rowC_7_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            image_diff_posterize_rowC_7_we0 <= ap_const_logic_1;
        else 
            image_diff_posterize_rowC_7_we0 <= ap_const_logic_0;
        end if; 
    end process;

    lshr_ln_fu_426_p4 <= ap_sig_allocacmp_j_3(7 downto 3);
    select_ln86_10_fu_924_p3 <= 
        ap_const_lv8_0 when (icmp_ln86_5_fu_912_p2(0) = '1') else 
        ap_const_lv8_80;
    select_ln86_12_fu_1003_p3 <= 
        ap_const_lv8_0 when (icmp_ln86_6_fu_991_p2(0) = '1') else 
        ap_const_lv8_80;
    select_ln86_14_fu_1082_p3 <= 
        ap_const_lv8_0 when (icmp_ln86_7_fu_1070_p2(0) = '1') else 
        ap_const_lv8_80;
    select_ln86_2_fu_608_p3 <= 
        ap_const_lv8_0 when (icmp_ln86_1_fu_596_p2(0) = '1') else 
        ap_const_lv8_80;
    select_ln86_4_fu_687_p3 <= 
        ap_const_lv8_0 when (icmp_ln86_2_fu_675_p2(0) = '1') else 
        ap_const_lv8_80;
    select_ln86_6_fu_766_p3 <= 
        ap_const_lv8_0 when (icmp_ln86_3_fu_754_p2(0) = '1') else 
        ap_const_lv8_80;
    select_ln86_8_fu_845_p3 <= 
        ap_const_lv8_0 when (icmp_ln86_4_fu_833_p2(0) = '1') else 
        ap_const_lv8_80;
    select_ln86_fu_529_p3 <= 
        ap_const_lv8_0 when (icmp_ln86_fu_517_p2(0) = '1') else 
        ap_const_lv8_80;
    sub_ln84_1_fu_572_p2 <= std_logic_vector(unsigned(ap_const_lv8_0) - unsigned(trunc_ln84_1_fu_560_p1));
    sub_ln84_2_fu_651_p2 <= std_logic_vector(unsigned(ap_const_lv8_0) - unsigned(trunc_ln84_2_fu_639_p1));
    sub_ln84_3_fu_730_p2 <= std_logic_vector(unsigned(ap_const_lv8_0) - unsigned(trunc_ln84_3_fu_718_p1));
    sub_ln84_4_fu_809_p2 <= std_logic_vector(unsigned(ap_const_lv8_0) - unsigned(trunc_ln84_4_fu_797_p1));
    sub_ln84_5_fu_888_p2 <= std_logic_vector(unsigned(ap_const_lv8_0) - unsigned(trunc_ln84_5_fu_876_p1));
    sub_ln84_6_fu_967_p2 <= std_logic_vector(unsigned(ap_const_lv8_0) - unsigned(trunc_ln84_6_fu_955_p1));
    sub_ln84_7_fu_1046_p2 <= std_logic_vector(unsigned(ap_const_lv8_0) - unsigned(trunc_ln84_7_fu_1034_p1));
    sub_ln84_fu_493_p2 <= std_logic_vector(unsigned(ap_const_lv8_0) - unsigned(trunc_ln84_fu_481_p1));
    tmp_10_fu_823_p4 <= diff_4_fu_815_p3(7 downto 5);
    tmp_11_fu_880_p3 <= diff_temp_5_fu_870_p2(8 downto 8);
    tmp_12_fu_902_p4 <= diff_5_fu_894_p3(7 downto 5);
    tmp_13_fu_959_p3 <= diff_temp_6_fu_949_p2(8 downto 8);
    tmp_14_fu_981_p4 <= diff_6_fu_973_p3(7 downto 5);
    tmp_15_fu_1038_p3 <= diff_temp_7_fu_1028_p2(8 downto 8);
    tmp_16_fu_1060_p4 <= diff_7_fu_1052_p3(7 downto 5);
    tmp_1_fu_485_p3 <= diff_temp_fu_475_p2(8 downto 8);
    tmp_2_fu_507_p4 <= diff_fu_499_p3(7 downto 5);
    tmp_3_fu_564_p3 <= diff_temp_1_fu_554_p2(8 downto 8);
    tmp_4_fu_586_p4 <= diff_1_fu_578_p3(7 downto 5);
    tmp_5_fu_643_p3 <= diff_temp_2_fu_633_p2(8 downto 8);
    tmp_6_fu_665_p4 <= diff_2_fu_657_p3(7 downto 5);
    tmp_7_fu_722_p3 <= diff_temp_3_fu_712_p2(8 downto 8);
    tmp_8_fu_744_p4 <= diff_3_fu_736_p3(7 downto 5);
    tmp_9_fu_801_p3 <= diff_temp_4_fu_791_p2(8 downto 8);
    tmp_fu_418_p3 <= ap_sig_allocacmp_j_3(8 downto 8);
    trunc_ln84_1_fu_560_p1 <= diff_temp_1_fu_554_p2(8 - 1 downto 0);
    trunc_ln84_2_fu_639_p1 <= diff_temp_2_fu_633_p2(8 - 1 downto 0);
    trunc_ln84_3_fu_718_p1 <= diff_temp_3_fu_712_p2(8 - 1 downto 0);
    trunc_ln84_4_fu_797_p1 <= diff_temp_4_fu_791_p2(8 - 1 downto 0);
    trunc_ln84_5_fu_876_p1 <= diff_temp_5_fu_870_p2(8 - 1 downto 0);
    trunc_ln84_6_fu_955_p1 <= diff_temp_6_fu_949_p2(8 - 1 downto 0);
    trunc_ln84_7_fu_1034_p1 <= diff_temp_7_fu_1028_p2(8 - 1 downto 0);
    trunc_ln84_fu_481_p1 <= diff_temp_fu_475_p2(8 - 1 downto 0);
    zext_ln81_10_fu_787_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(image_diff_posterize_rowB_4_q0),9));
    zext_ln81_11_fu_862_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(image_diff_posterize_rowA_5_q0),9));
    zext_ln81_12_fu_866_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(image_diff_posterize_rowB_5_q0),9));
    zext_ln81_13_fu_941_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(image_diff_posterize_rowA_6_q0),9));
    zext_ln81_14_fu_945_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(image_diff_posterize_rowB_6_q0),9));
    zext_ln81_15_fu_1020_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(image_diff_posterize_rowA_7_q0),9));
    zext_ln81_16_fu_1024_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(image_diff_posterize_rowB_7_q0),9));
    zext_ln81_1_fu_467_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(image_diff_posterize_rowA_0_q0),9));
    zext_ln81_2_fu_471_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(image_diff_posterize_rowB_0_q0),9));
    zext_ln81_3_fu_546_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(image_diff_posterize_rowA_1_q0),9));
    zext_ln81_4_fu_550_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(image_diff_posterize_rowB_1_q0),9));
    zext_ln81_5_fu_625_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(image_diff_posterize_rowA_2_q0),9));
    zext_ln81_6_fu_629_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(image_diff_posterize_rowB_2_q0),9));
    zext_ln81_7_fu_704_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(image_diff_posterize_rowA_3_q0),9));
    zext_ln81_8_fu_708_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(image_diff_posterize_rowB_3_q0),9));
    zext_ln81_9_fu_783_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(image_diff_posterize_rowA_4_q0),9));
    zext_ln81_fu_436_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln_fu_426_p4),64));
end behav;
